"use client";
import {useEffect,useState} from "react";
const API=(process.env.NEXT_PUBLIC_API_BASE||"https://grabzone.nemesiseditzx984.workers.dev").replace(/\/$/,"");
async function api(path:string,init?:RequestInit){
 const target=path==="/api/auth"?"/api/admin-auth":path==="/api/table"?"/api/d1":path;
 const headers:any={"Content-Type":"application/json",...(init?.headers||{})};
 const token=typeof window!=="undefined"?localStorage.getItem("grabzone_admin_token"):"";if(token)headers["X-GrabZone-Token"]=token;
 let body=init?.body;if(path==="/api/table"){const raw=body?JSON.parse(String(body)):{};body=JSON.stringify({type:"table",...raw})}
 const r=await fetch(API+target,{...init,body,credentials:"include",headers});const d=await r.json().catch(()=>({}));
 if(d?.session_token&&typeof window!=="undefined")localStorage.setItem("grabzone_admin_token",d.session_token);
 if(!r.ok)throw new Error(d?.error||("Request failed ("+r.status+")"));return d}
export default function Admin(){const [auth,setAuth]=useState(false),[login,setLogin]=useState({email:"",password:""}),[err,setErr]=useState(""),[orders,setOrders]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[tab,setTab]=useState("Overview");
 async function load(){try{const s=await api("/api/auth",{method:"GET"});if(!s.authenticated){setAuth(false);return}setAuth(true);const [o,p]=await Promise.all([api("/api/table",{method:"POST",body:JSON.stringify({table:"orders",action:"select",columns:"*",orders:[{column:"created_at",ascending:false}],limit:100})}),api("/api/table",{method:"POST",body:JSON.stringify({table:"products",action:"select",columns:"*",orders:[{column:"created_at",ascending:false}],limit:100})})]);setOrders(o.data||[]);setProducts(p.data||[])}catch(e){setErr(e instanceof Error?e.message:"Could not load admin.")}}
 useEffect(()=>{load()},[]);
 async function signIn(e:React.FormEvent){e.preventDefault();setErr("");try{await api("/api/auth",{method:"POST",body:JSON.stringify(login)});await load()}catch(e){setErr(e instanceof Error?e.message:"Login failed.")}}
 async function logout(){try{await api("/api/auth",{method:"POST",body:JSON.stringify({action:"logout"})})}finally{localStorage.removeItem("grabzone_admin_token");setAuth(false)}}
 if(!auth)return <main className="adminLogin"><form onSubmit={signIn} className="adminCard"><div className="logo">G<span>RABZONE</span></div><div className="eyebrow">CONTROL CENTER</div><h1>Admin login</h1><input required type="email" placeholder="Admin email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input required type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="primary full">Sign in</button>{err&&<p className="error">{err}</p>}</form></main>
 const delivered=orders.filter(o=>String(o.status).toLowerCase().includes("deliver")).length,pending=orders.filter(o=>!["Delivered","Cancelled"].includes(o.status)).length,revenue=orders.reduce((s,o)=>s+Number(o.total||0),0);
 return <main className="admin"><aside><div className="logo">G<span>RABZONE</span></div>{["Overview","Orders","Products","Tracking","Referral Codes","Notices","Payment","Policies"].map(x=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x}</button>)}<button className="logout" onClick={logout}>Log out</button></aside><section className="adminMain"><header><div><div className="eyebrow">WEBSITE CONTROL CENTER</div><h1>{tab}</h1></div><a className="secondary" href="/">View store</a></header>{tab==="Overview"&&<><div className="metrics"><div><small>Total orders</small><b>{orders.length}</b></div><div><small>Pending</small><b>{pending}</b></div><div><small>Delivered</small><b>{delivered}</b></div><div><small>Revenue</small><b>৳{Math.round(revenue).toLocaleString("en-BD")}</b></div></div><div className="adminPanel"><h2>Recent orders</h2>{orders.slice(0,10).map(o=><div className="orderRow" key={o.id}><b>#{o.order_number}</b><span>{o.customer_name}</span><span>{o.phone}</span><span>{o.status}</span><b>৳{Number(o.total||0).toLocaleString("en-BD")}</b></div>)}</div></>}{tab==="Orders"&&<div className="adminPanel"><h2>Orders</h2>{orders.map(o=><div className="orderRow" key={o.id}><b>#{o.order_number}</b><span>{o.customer_name}</span><span>{o.phone}</span><span>{o.district}</span><span>{o.status}</span><b>৳{Number(o.total||0).toLocaleString("en-BD")}</b></div>)}</div>}{tab==="Products"&&<div className="adminPanel"><h2>Products</h2>{products.map(p=><div className="orderRow" key={p.id}><b>{p.name}</b><span>{p.category}</span><span>৳{p.price}</span><span>{p.published?"Published":"Hidden"}</span></div>)}</div>}{!["Overview","Orders","Products"].includes(tab)&&<div className="adminPanel"><h2>{tab}</h2><p>This control area is reserved for the connected GrabZone D1-backed management module. The clean rebuild keeps these controls separated so they can be expanded without touching the storefront.</p></div>}</section></main>}
