const C=window.GRABZONE_CONFIG;let sb=null;
if(C&&!C.supabaseUrl.includes("PASTE_"))sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
const $=id=>document.getElementById(id);
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
async function login(){try{if(!sb){$("loginMsg").textContent="Configure config.js first.";return}const em=$("email").value.trim(),pw=$("password").value;if(!em||!pw){$("loginMsg").textContent="Enter email and password.";return}const{error}=await sb.auth.signInWithPassword({email:em,password:pw});$("loginMsg").textContent=error?error.message:"";if(!error)showApp()}catch(e){$("loginMsg").textContent=e.message}}
async function logout(){await sb.auth.signOut();location.reload()}
function showApp(){$("loginBox").classList.add("hidden");$("app").classList.remove("hidden");loadSettings();loadProducts();loadNotices()}
async function uploadImage(file){if(!file)throw new Error("Choose an image.");const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=`${crypto.randomUUID()}.${ext}`;const{error}=await sb.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return sb.storage.from("product-images").getPublicUrl(path).data.publicUrl}
const fields=["store_name","tagline","hero_eyebrow","hero_title","hero_title_em","hero_description","hero_button_text","hero_button_link","how_button_text","how_button_link","offer_title","offer_message","offer_code","collection_eyebrow","collection_title","how_eyebrow","how_title","step1_title","step1_body","step2_title","step2_body","step3_title","step3_body","referral_eyebrow","referral_title","referral_body","referral_button_text","footer_text","whatsapp","instagram","messenger","header_link1_label","header_link1_url","header_link2_label","header_link2_url","header_link3_label","header_link3_url","custom_css"];
async function loadSettings(){const{data,error}=await sb.from("site_settings").select("*").eq("id",1).maybeSingle();if(error){$("settingsMsg").textContent=error.message;return}if(!data)return;fields.forEach(k=>{const el=$("s_"+k);if(el)el.value=data[k]??""});$("s_primary").value=data.primary_color||"#111111";$("s_bg").value=data.page_background||"#ffffff";$("s_show_notice").value=String(data.show_notice??true);$("s_show_offer").value=String(data.show_offer??true);$("s_show_how").value=String(data.show_how??true);$("s_show_ref").value=String(data.show_referral??true)}
async function saveSettings(){try{$("settingsMsg").textContent=" Saving...";const patch={};fields.forEach(k=>{const el=$("s_"+k);if(el)patch[k]=el.value});const logo=$("s_logo"),hero=$("s_hero");if(logo?.files?.[0])patch.logo_url=await uploadImage(logo.files[0]);if(hero?.files?.[0])patch.hero_image_url=await uploadImage(hero.files[0]);patch.primary_color=$("s_primary").value;patch.page_background=$("s_bg").value;patch.show_notice=$("s_show_notice").value==="true";patch.show_offer=$("s_show_offer").value==="true";patch.show_how=$("s_show_how").value==="true";patch.show_referral=$("s_show_ref").value==="true";patch.updated_at=new Date().toISOString();const{error}=await sb.from("site_settings").upsert({id:1,...patch},{onConflict:"id"});if(error)throw error;$("settingsMsg").textContent=" Saved successfully. Refresh the storefront.";await loadSettings()}catch(e){$("settingsMsg").textContent=" "+e.message}}
async function addProduct(){try{const n=$("name"),cat=$("category"),pr=$("price"),old=$("oldPrice"),tag=$("tag"),desc=$("description"),pub=$("published"),img=$("image");if(!n.value.trim()||!cat.value.trim()||!pr.value){$("productMsg").textContent=" Enter product name, category and price.";return} $("productMsg").textContent=" Uploading image...";const imageUrl=await uploadImage(img.files?.[0]);const{error}=await sb.from("products").insert({name:n.value.trim(),category:cat.value.trim(),price:Number(pr.value),old_price:old.value?Number(old.value):null,image_url:imageUrl,tag:tag.value.trim(),description:desc.value.trim(),published:pub.value==="true"});if(error)throw error;$("productMsg").textContent=" Saved.";["name","category","price","oldPrice","tag","description"].forEach(id=>$(id).value="");img.value="";loadProducts()}catch(e){$("productMsg").textContent=" "+e.message}}
async function loadProducts(){const{data,error}=await sb.from("products").select("*").order("created_at",{ascending:false});if(error){$("products").innerHTML=esc(error.message);return}$("products").innerHTML=(data||[]).map(p=>`<div class="item"><img src="${esc(p.image_url)}"><div><b>${esc(p.name)}</b><div>${esc(p.category)} · ৳${Number(p.price).toLocaleString()} · ${p.published?"Published":"Hidden"}</div></div><div><button onclick="toggleProduct('${p.id}',${p.published})">${p.published?"Hide":"Publish"}</button> <button class="light" onclick="deleteProduct('${p.id}')">Delete</button></div></div>`).join("")||"<p>No products yet.</p>"}
async function toggleProduct(id,p){await sb.from("products").update({published:!p,updated_at:new Date().toISOString()}).eq("id",id);loadProducts()}
async function deleteProduct(id){if(confirm("Delete this product?")){await sb.from("products").delete().eq("id",id);loadProducts()}}
async function addNotice(){const t=$("noticeTitle"),m=$("noticeMessage");if(!t.value.trim()||!m.value.trim()){alert("Enter notice title and message.");return}const{error}=await sb.from("notices").insert({title:t.value.trim(),message:m.value.trim(),sort_order:Number($("noticeOrder").value||0),active:true});if(error){alert(error.message);return}t.value="";m.value="";loadNotices()}
async function loadNotices(){const{data,error}=await sb.from("notices").select("*").order("sort_order",{ascending:true});if(error){$("notices").innerHTML=esc(error.message);return}$("notices").innerHTML=(data||[]).map(n=>`<div class="notice"><b>${esc(n.title)}</b><div>${esc(n.message)}</div><button onclick="toggleNotice('${n.id}',${n.active})">${n.active?"Hide":"Show"}</button> <button class="light" onclick="deleteNotice('${n.id}')">Delete</button></div>`).join("")||"<p>No notices yet.</p>"}
async function toggleNotice(id,p){await sb.from("notices").update({active:!p}).eq("id",id);loadNotices()}
async function deleteNotice(id){if(confirm("Delete this notice?")){await sb.from("notices").delete().eq("id",id);loadNotices()}}
(async()=>{if(sb){const{data}=await sb.auth.getSession();if(data.session)showApp()}})();
