const PK="nova_store_v4",NK="nova_notices_v4",SK="nova_settings_v4";
function login(){const u=document.getElementById("adminUser").value,p=document.getElementById("adminPass").value;if(u===getSettings().adminUsername&&p===getSettings().adminPassword){sessionStorage.setItem("nova_admin","1");showAdmin()}else document.getElementById("loginError").textContent="Invalid login."}
function logout(){sessionStorage.removeItem("nova_admin");location.reload()}
function showAdmin(){document.getElementById("login").classList.add("hidden");document.getElementById("adminApp").classList.remove("hidden");document.getElementById("adminStoreName").textContent=getSettings().name;renderAdminProducts();renderAdminNotices();renderSettings()}
function getSettings(){try{return {...window.STORE_DEFAULTS,...JSON.parse(localStorage.getItem(SK)||"{}")}}catch{return {...window.STORE_DEFAULTS}}}
function products(){try{return JSON.parse(localStorage.getItem(PK))||demoProducts}catch{return demoProducts}}
const demoProducts=[
{id:"p1",name:"Portable Electric Kettle",category:"Home & Kitchen",price:990,oldPrice:1250,image:"https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=900&q=85",tag:"HOT DEAL",description:"Compact portable electric kettle.",published:true},
{id:"p2",name:"Plextone RX3 PLUS Wired Gaming Earphone",category:"Smart Gadgets",price:690,oldPrice:850,image:"https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=85",tag:"GAMING",description:"Wired gaming earphone.",published:true},
{id:"p3",name:"Siren Alarm Lock For Security",category:"Security",price:790,oldPrice:990,image:"https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=900&q=85",tag:"POPULAR",description:"Compact alarm-style security lock.",published:true},
{id:"p4",name:"Mini Power Bank",category:"Smart Gadgets",price:790,oldPrice:950,image:"https://images.unsplash.com/photo-1609592424937-3e7f4e4b2e47?auto=format&fit=crop&w=900&q=85",tag:"NEW",description:"Portable backup power.",published:true},
{id:"p5",name:"Portable Phone Stand",category:"Smart Gadgets",price:390,oldPrice:490,image:"https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=85",tag:"VALUE",description:"Foldable phone stand.",published:true},
{id:"p6",name:"Kemei Grooming Kit",category:"Fashion Item",price:890,oldPrice:1090,image:"https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=900&q=85",tag:"BEST SELLER",description:"Multi-purpose grooming kit.",published:true}
]
function save(x){localStorage.setItem(PK,JSON.stringify(x))}
function renderAdminProducts(){const x=products();document.getElementById("adminProducts").innerHTML=`<table class="admin-table"><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>PRICE</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>${x.map((p,i)=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.category)}</td><td>৳${Number(p.price).toLocaleString()}</td><td><span class="status ${p.published?"on":""}">${p.published?"Published":"Hidden"}</span></td><td><div class="admin-actions"><button class="small-btn" onclick="openProduct(${i})">Edit</button><button class="small-btn" onclick="toggleProduct(${i})">${p.published?"Hide":"Publish"}</button><button class="small-btn" onclick="deleteProduct(${i})">Delete</button></div></td></tr>`).join("")}</tbody></table>`}
function openProduct(i=-1){const p=i>=0?products()[i]:{id:"p"+Date.now(),name:"",category:"",price:"",oldPrice:"",image:"",tag:"",description:"",published:true};document.getElementById("modalContent").innerHTML=`<h2>${i<0?"Add":"Edit"} product</h2><form class="form-grid" onsubmit="saveProduct(event,${i})"><label>Product name<input id="pn" required value="${escAttr(p.name)}"></label><label>Category<input id="pc" required value="${escAttr(p.category)}"></label><label>Price<input id="pp" type="number" required value="${p.price}"></label><label>Old price<input id="po" type="number" value="${p.oldPrice||""}"></label><label class="full">Image URL<input id="pi" required value="${escAttr(p.image)}"></label><label>Tag<input id="pt" value="${escAttr(p.tag||"")}"></label><label>Published<select id="pub"><option value="1" ${p.published?"selected":""}>Yes</option><option value="0" ${!p.published?"selected":""}>No</option></select></label><label class="full">Description<textarea id="pd">${esc(p.description||"")}</textarea></label><div class="full"><button class="btn btn-dark">Save product</button></div></form>`;openModal()}
function saveProduct(e,i){e.preventDefault();const x=products();const p={id:i>=0?x[i].id:"p"+Date.now(),name:pn.value.trim(),category:pc.value.trim(),price:Number(pp.value),oldPrice:po.value?Number(po.value):"",image:pi.value.trim(),tag:pt.value.trim(),description:pd.value.trim(),published:pub.value==="1"};i>=0?x[i]=p:x.unshift(p);save(x);closeModal();renderAdminProducts()}
function toggleProduct(i){const x=products();x[i].published=!x[i].published;save(x);renderAdminProducts()}
function deleteProduct(i){if(confirm("Delete this product?")){const x=products();x.splice(i,1);save(x);renderAdminProducts()}}
function notices(){try{return JSON.parse(localStorage.getItem(NK))||[]}catch{return[]}}
function saveNotices(x){localStorage.setItem(NK,JSON.stringify(x))}
function renderAdminNotices(){const x=notices();document.getElementById("adminNotices").innerHTML=`<table class="admin-table"><thead><tr><th>TITLE</th><th>MESSAGE</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>${x.map((n,i)=>`<tr><td><b>${esc(n.title)}</b></td><td>${esc(n.text)}</td><td><span class="status ${n.active?"on":""}">${n.active?"Active":"Hidden"}</span></td><td><div class="admin-actions"><button class="small-btn" onclick="openNotice(${i})">Edit</button><button class="small-btn" onclick="toggleNotice(${i})">${n.active?"Hide":"Show"}</button><button class="small-btn" onclick="deleteNotice(${i})">Delete</button></div></td></tr>`).join("")}</tbody></table>`}
function openNotice(i=-1){const n=i>=0?notices()[i]:{id:"n"+Date.now(),title:"",text:"",active:true};document.getElementById("modalContent").innerHTML=`<h2>${i<0?"Add":"Edit"} notice</h2><form class="form-grid" onsubmit="saveNotice(event,${i})"><label>Title<input id="nt" required value="${escAttr(n.title)}"></label><label>Active<select id="na"><option value="1" ${n.active?"selected":""}>Yes</option><option value="0" ${!n.active?"selected":""}>No</option></select></label><label class="full">Message<textarea id="nx" required>${esc(n.text)}</textarea></label><div class="full"><button class="btn btn-dark">Save notice</button></div></form>`;openModal()}
function saveNotice(e,i){e.preventDefault();const x=notices();const n={id:i>=0?x[i].id:"n"+Date.now(),title:nt.value.trim(),text:nx.value.trim(),active:na.value==="1"};i>=0?x[i]=n:x.unshift(n);saveNotices(x);closeModal();renderAdminNotices()}
function toggleNotice(i){const x=notices();x[i].active=!x[i].active;saveNotices(x);renderAdminNotices()}
function deleteNotice(i){if(confirm("Delete this notice?")){const x=notices();x.splice(i,1);saveNotices(x);renderAdminNotices()}}
function renderSettings(){const s=getSettings();document.getElementById("settingsForm").innerHTML=`<label>Store name<input id="sn" value="${escAttr(s.name)}"></label><label>Currency symbol<input id="sc" value="${escAttr(s.currency)}"></label><label>WhatsApp DM link<input id="sw" value="${escAttr(s.whatsapp)}"></label><label>Messenger link<input id="sm" value="${escAttr(s.messenger)}"></label><label>Instagram link<input id="si" value="${escAttr(s.instagram)}"></label><label>Admin username<input id="su" value="${escAttr(s.adminUsername)}"></label><label>Admin password<input id="sp" type="password" value="${escAttr(s.adminPassword)}"></label><div class="full"><button class="btn btn-dark" type="button" onclick="saveSettings()">Save settings</button></div>`}
function saveSettings(){localStorage.setItem(SK,JSON.stringify({name:sn.value.trim()||"GRABZONE",currency:sc.value.trim()||"৳",whatsapp:sw.value.trim(),messenger:sm.value.trim(),instagram:si.value.trim(),adminUsername:su.value.trim(),adminPassword:sp.value}));alert("Settings saved.")}
function exportData(){const data={products:products(),notices:notices(),settings:getSettings()};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="nova-store-backup.json";a.click()}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.products)localStorage.setItem(PK,JSON.stringify(d.products));if(d.notices)localStorage.setItem(NK,JSON.stringify(d.notices));if(d.settings)localStorage.setItem(SK,JSON.stringify(d.settings));alert("Backup imported.");showAdmin()}catch{alert("Invalid backup file.")}};r.readAsText(f)}
function resetDemo(){if(confirm("Reset website content to demo data?")){localStorage.removeItem(PK);localStorage.removeItem(NK);localStorage.removeItem(SK);showAdmin()}}
function openModal(){document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function escAttr(x){return esc(x).replace(/`/g,"&#96;")}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));document.getElementById("tab-"+b.dataset.tab).classList.remove("hidden")}));
if(sessionStorage.getItem("nova_admin")==="1")showAdmin();