(() => {
'use strict';
const C=window.GRABZONE_CONFIG||{}, SUPABASE=window.supabase;
const sb=SUPABASE&&C.supabaseUrl&&!String(C.supabaseUrl).includes('PASTE_')?SUPABASE.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
const CART_KEY='grabzone_cart_v2',BUY_NOW_KEY='grabzone_buy_now_v2',currency=C.currency||'৳';
let checkoutItems=[],site={};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}};
const money=n=>currency+Number(n||0).toLocaleString('en-BD');
const getSource=()=>{const buy=read(BUY_NOW_KEY,null);return Array.isArray(buy)&&buy.length?buy:read(CART_KEY,[])};
function msg(t,error=false){const e=$('checkoutMessage');if(e){e.textContent=t||'';e.className='checkout-message'+(error?' error':'')}}
function subtotal(){return checkoutItems.reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||0),0)}
async function loadSite(){if(!sb)return;const{data}=await sb.from('site_settings').select('store_name,logo_url').eq('id',1).maybeSingle();site=data||{};document.title='Checkout — '+(site.store_name||'GRABZONE');if(site.logo_url&&$('checkoutLogo'))$('checkoutLogo').src=site.logo_url}
async function hydrate(){const raw=getSource();if(!raw.length){render();return}if(!sb){checkoutItems=raw;render();return}const ids=[...new Set(raw.map(x=>x.product_id).filter(Boolean))];const{data,error}=await sb.from('products').select('id,name,price,image_url,published').in('id',ids);if(error){console.error(error);checkoutItems=raw;render();return}const map=new Map((data||[]).map(p=>[p.id,p]));checkoutItems=raw.map(x=>{const p=map.get(x.product_id);if(!p)return null;return{product_id:p.id,name:p.name,image_url:p.image_url,price:Number(p.price||0),quantity:Math.max(1,Number(x.quantity||1))}}).filter(Boolean);render()}
function render(){const box=$('checkoutItems'),side=$('checkoutItemsSide'),empty=$('checkoutEmpty'),form=$('checkoutForm');if(!checkoutItems.length){if(box)box.innerHTML='';if(side)side.innerHTML='';if(empty)empty.hidden=false;if(form)form.hidden=true;return}if(empty)empty.hidden=true;if(form)form.hidden=false;box.innerHTML=checkoutItems.map(i=>`<div class="checkout-item"><img src="${esc(i.image_url)}" alt="${esc(i.name)}"><div class="checkout-item-info"><strong>${esc(i.name)}</strong><span>Quantity: ${i.quantity}</span></div><b>${money(i.price*i.quantity)}</b></div>`).join('');side.innerHTML=checkoutItems.map(i=>`<div class="summary-product"><img src="${esc(i.image_url)}" alt=""><div><strong>${esc(i.name)}</strong><span>Qty ${i.quantity}</span></div><b>${money(i.price*i.quantity)}</b></div>`).join('');const shipping=Number(window.GRABZONE_SHIPPING||0),sub=subtotal();$('checkoutSubtotal').textContent=money(sub);$('checkoutShipping').textContent=money(shipping);$('checkoutTotal').textContent=money(sub+shipping)}
function formData(){return{customer_name:$('customerName').value.trim(),phone:$('customerPhone').value.trim(),email:$('customerEmail').value.trim(),division:$('division').value.trim(),district:$('district').value.trim(),upazila:$('upazila').value.trim(),address:$('address').value.trim(),referral_code:$('referralCode').value.trim()}}
function validate(d){if(!d.customer_name||!d.phone||!d.email||!d.division||!d.district||!d.address)return'Please complete all required fields.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))return'Please enter a valid email address.';if(!/^[0-9+\-\s()]{7,20}$/.test(d.phone))return'Please enter a valid mobile number.';return checkoutItems.length?'':'Your order is empty.'}
async function submit(e){e.preventDefault();const d=formData(),bad=validate(d);if(bad){msg(bad,true);return}const b=$('placeOrderBtn');b.disabled=true;b.textContent='Placing order…';msg('');const shipping=Number(window.GRABZONE_SHIPPING||0);const payload={customer_name:d.customer_name,email:d.email,phone:d.phone,division:d.division,district:d.district,upazila:d.upazila,address:d.address,referral_code:d.referral_code||null,payment_method:'Cash on Delivery',shipping_charge:shipping,items:checkoutItems.map(i=>({product_id:i.product_id,product_name:i.name,image_url:i.image_url,quantity:Number(i.quantity),unit_price:Number(i.price)})),subtotal:subtotal(),total:subtotal()+shipping};try{if(!sb)throw new Error('Order service is not configured.');const{data:order,error}=await sb.rpc('create_public_order',{payload});if(error)throw error;if(!order?.id||!order?.order_number)throw new Error('Order could not be created.');let emailSent=true;try{const r=await fetch('/api/send-order-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'order_created',orderNumber:order.order_number,order:payload})});emailSent=r.ok}catch(err){console.warn('Email failed',err);emailSent=false}localStorage.removeItem(CART_KEY);localStorage.removeItem(BUY_NOW_KEY);$('checkoutForm').hidden=true;$('checkoutSuccess').hidden=false;$('successOrderNumber').textContent=order.order_number;$('successEmailNote').textContent=emailSent?'A confirmation email was sent to '+d.email+'.':'Your order is confirmed. The confirmation email could not be sent right now.';window.scrollTo({top:0,behavior:'smooth'})}catch(err){console.error(err);msg(err.message||'Could not place your order. Please try again.',true);b.disabled=false;b.textContent='Confirm Order'}}
document.addEventListener('DOMContentLoaded',async()=>{$('checkoutForm')?.addEventListener('submit',submit);await loadSite();await hydrate()});
})();