PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,old_price REAL,image_url TEXT NOT NULL,tag TEXT,description TEXT,published INTEGER NOT NULL DEFAULT 1,business_koro_product_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS products_published_idx ON products(published);
CREATE TABLE IF NOT EXISTS product_images (id TEXT PRIMARY KEY,product_id TEXT NOT NULL,image_url TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,is_main INTEGER NOT NULL DEFAULT 0,created_at TEXT);
CREATE INDEX IF NOT EXISTS product_images_product_idx ON product_images(product_id,sort_order);
CREATE TABLE IF NOT EXISTS notices (id TEXT PRIMARY KEY,title TEXT NOT NULL,message TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS notices_active_idx ON notices(active,sort_order);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY,order_no INTEGER NOT NULL UNIQUE,order_number TEXT NOT NULL UNIQUE,customer_name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,division TEXT NOT NULL,district TEXT NOT NULL,upazila TEXT,address TEXT NOT NULL,referral_code TEXT,referral_discount REAL NOT NULL DEFAULT 0,discount_amount REAL NOT NULL DEFAULT 0,referral_admin_name TEXT,payment_method TEXT NOT NULL DEFAULT 'Cash on Delivery',shipping_charge REAL NOT NULL DEFAULT 130,subtotal REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'New',admin_note TEXT,tracking_number TEXT,tracking_url TEXT,tracking_provider TEXT,public_tracking_id TEXT NOT NULL UNIQUE,business_koro_sent_at TEXT,business_koro_order_ids TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS orders_created_idx ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS orders_tracking_idx ON orders(tracking_number);
CREATE INDEX IF NOT EXISTS orders_public_tracking_idx ON orders(public_tracking_id);
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY,order_id TEXT NOT NULL,product_id TEXT,product_name TEXT NOT NULL,image_url TEXT,quantity INTEGER NOT NULL,unit_price REAL NOT NULL DEFAULT 0,line_total REAL NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items(order_id,id);
CREATE TABLE IF NOT EXISTS referral_codes (id TEXT PRIMARY KEY,admin_name TEXT NOT NULL,admin_phone TEXT,admin_email TEXT,code TEXT NOT NULL,benefit_type TEXT NOT NULL DEFAULT 'fixed',benefit_value REAL NOT NULL DEFAULT 0,min_order_amount REAL NOT NULL DEFAULT 0,max_discount_amount REAL,usage_limit INTEGER,used_count INTEGER NOT NULL DEFAULT 0,starts_at TEXT,expires_at TEXT,active INTEGER NOT NULL DEFAULT 1,note TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,owner_name TEXT,commission_type TEXT NOT NULL DEFAULT 'percentage',commission_value REAL NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX IF NOT EXISTS referral_codes_upper_idx ON referral_codes(upper(code));
CREATE TABLE IF NOT EXISTS site_settings (id INTEGER PRIMARY KEY,store_name TEXT,tagline TEXT,currency TEXT,logo_url TEXT,favicon_url TEXT,hero_image_url TEXT,hero_eyebrow TEXT,hero_title TEXT,hero_title_em TEXT,hero_description TEXT,hero_button_text TEXT,hero_button_link TEXT,how_button_text TEXT,how_button_link TEXT,offer_title TEXT,offer_message TEXT,offer_code TEXT,collection_eyebrow TEXT,collection_title TEXT,how_eyebrow TEXT,how_title TEXT,step1_title TEXT,step1_body TEXT,step2_title TEXT,step2_body TEXT,step3_title TEXT,step3_body TEXT,referral_eyebrow TEXT,referral_title TEXT,referral_body TEXT,referral_button_text TEXT,footer_text TEXT,whatsapp TEXT,messenger TEXT,instagram TEXT,header_link1_label TEXT,header_link1_url TEXT,header_link2_label TEXT,header_link2_url TEXT,header_link3_label TEXT,header_link3_url TEXT,primary_color TEXT,page_background TEXT,custom_css TEXT,show_notice INTEGER NOT NULL DEFAULT 1,show_offer INTEGER NOT NULL DEFAULT 1,show_how INTEGER NOT NULL DEFAULT 1,show_referral INTEGER NOT NULL DEFAULT 1,updated_at TEXT,animations_enabled INTEGER NOT NULL DEFAULT 1,page_load INTEGER NOT NULL DEFAULT 1,scroll_reveal INTEGER NOT NULL DEFAULT 1,product_hover INTEGER NOT NULL DEFAULT 1,button_effects INTEGER NOT NULL DEFAULT 1,hero_animation INTEGER NOT NULL DEFAULT 1,floating_effects INTEGER NOT NULL DEFAULT 1,notice_animation INTEGER NOT NULL DEFAULT 1,animation_speed TEXT DEFAULT 'normal',magnetic_cursor INTEGER NOT NULL DEFAULT 1,text_reveal INTEGER NOT NULL DEFAULT 1,image_parallax INTEGER NOT NULL DEFAULT 1,scroll_velocity INTEGER NOT NULL DEFAULT 1,product_stagger INTEGER NOT NULL DEFAULT 1,marquee_motion INTEGER NOT NULL DEFAULT 1,header_scroll INTEGER NOT NULL DEFAULT 1,premium_hover_glow INTEGER NOT NULL DEFAULT 1,section_transitions INTEGER NOT NULL DEFAULT 1,product_entrance INTEGER NOT NULL DEFAULT 1,product_3d_tilt INTEGER NOT NULL DEFAULT 1,product_image_zoom INTEGER NOT NULL DEFAULT 1,product_image_parallax INTEGER NOT NULL DEFAULT 1,product_cursor_spotlight INTEGER NOT NULL DEFAULT 1,product_shine INTEGER NOT NULL DEFAULT 1,product_hover_lift INTEGER NOT NULL DEFAULT 1,product_featured_glow INTEGER NOT NULL DEFAULT 1,payment_methods TEXT,product_display_mode TEXT,product_shuffle_seed TEXT,product_display_updated_at TEXT);
CREATE TABLE IF NOT EXISTS billboards (id TEXT PRIMARY KEY,title TEXT,eyebrow TEXT,message TEXT,image_url TEXT NOT NULL,button_text TEXT DEFAULT 'Shop Now →',link_url TEXT,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS billboards_active_idx ON billboards(active,sort_order,created_at);
CREATE TABLE IF NOT EXISTS billboard_settings (id INTEGER PRIMARY KEY,autoplay INTEGER NOT NULL DEFAULT 1,interval_ms INTEGER NOT NULL DEFAULT 5000,transition TEXT NOT NULL DEFAULT 'slide',show_arrows INTEGER NOT NULL DEFAULT 1,show_dots INTEGER NOT NULL DEFAULT 1,updated_at TEXT);
CREATE TABLE IF NOT EXISTS store_policies (id INTEGER PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 1,accent_color TEXT,accent_color_2 TEXT,background_color TEXT,card_color TEXT,animation_enabled INTEGER NOT NULL DEFAULT 1,content TEXT NOT NULL DEFAULT '{}',updated_at TEXT);
INSERT OR IGNORE INTO billboard_settings (id) VALUES (1);

-- GrabPoints one-time reward vouchers
CREATE TABLE IF NOT EXISTS rewards_vouchers (code TEXT PRIMARY KEY,member_id TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,points_redeemed INTEGER NOT NULL,value REAL NOT NULL,status TEXT NOT NULL DEFAULT 'UNUSED',expires_at TEXT NOT NULL,used_at TEXT,used_order_id TEXT,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS rewards_vouchers_member_idx ON rewards_vouchers(member_id,created_at DESC);
CREATE INDEX IF NOT EXISTS rewards_vouchers_phone_idx ON rewards_vouchers(phone,status,expires_at);
CREATE INDEX IF NOT EXISTS rewards_vouchers_status_idx ON rewards_vouchers(status,expires_at);

CREATE TABLE IF NOT EXISTS customer_points (phone TEXT PRIMARY KEY, points INTEGER NOT NULL DEFAULT 0, total_earned INTEGER NOT NULL DEFAULT 0, total_redeemed INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS grabpoints_ledger (id TEXT PRIMARY KEY, phone TEXT NOT NULL, order_id TEXT, points INTEGER NOT NULL, type TEXT NOT NULL, reference TEXT, reason TEXT, admin_id TEXT, balance_after INTEGER, qualifying_points INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, UNIQUE(order_id,type));
CREATE INDEX IF NOT EXISTS grabpoints_ledger_phone_idx ON grabpoints_ledger(phone,created_at DESC);
CREATE TABLE IF NOT EXISTS rewards_tx_guard(ok INTEGER PRIMARY KEY CHECK(ok=1));

CREATE TABLE IF NOT EXISTS membership_tiers (tier TEXT PRIMARY KEY,min_points INTEGER NOT NULL,cashback_percent REAL NOT NULL DEFAULT 0,discount_percent REAL NOT NULL DEFAULT 0,benefits TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL);
