(()=>{const id='gzRedeemMotionV2';if(document.getElementById(id))return;const s=document.createElement('style');s.id=id;s.textContent=`
/* Advanced verification motion — matches the current gz-rf redemption DOM. */
.gz-rf-pin-checking .gz-rf-pin-digit{animation:gzBoxLift .72s cubic-bezier(.2,.85,.2,1) both!important;border-color:#ff7a00!important;box-shadow:0 0 0 4px #ff7a0010,0 15px 30px #ff7a0020!important}
.gz-rf-pin-checking .gz-rf-pin-digit:nth-child(1){animation-delay:0s}.gz-rf-pin-checking .gz-rf-pin-digit:nth-child(2){animation-delay:.07s}.gz-rf-pin-checking .gz-rf-pin-digit:nth-child(3){animation-delay:.14s}.gz-rf-pin-checking .gz-rf-pin-digit:nth-child(4){animation-delay:.21s}.gz-rf-pin-checking .gz-rf-pin-digit:nth-child(5){animation-delay:.28s}.gz-rf-pin-checking .gz-rf-pin-digit:nth-child(6){animation-delay:.35s}
.gz-rf-pin-checking .gz-rf-pin-digits{animation:gzDigitsFloat .9s ease-in-out both}
.gz-rf-pin-checking .gz-rf-pin-card{overflow:hidden}
.gz-rf-pin-checking .gz-rf-pin-icon{position:relative}
.gz-rf-pin-checking .gz-rf-pin-icon:before{content:'';position:absolute;inset:-16px;border-radius:50%;border:1px dashed #ff7a0070;animation:gzOrbit 1.2s linear infinite}
.gz-rf-pin-checking .gz-rf-pin-icon:after{content:'';position:absolute;inset:-29px;border-radius:50%;border:1px solid #ff7a0020;animation:gzRing 1.3s ease-out infinite}
.gz-rf-pin-checking .gz-rf-pin-status{animation:gzStatus 1s ease-in-out infinite}
.gz-rf-pin-card.is-error .gz-rf-pin-digit{animation:gzWrong .5s both!important}.gz-rf-pin-card.is-success .gz-rf-pin-digit{animation:gzCorrect .58s cubic-bezier(.2,.9,.2,1) both!important}
.gz-rf-pin-card.is-success .gz-rf-pin-digit:nth-child(2){animation-delay:.05s}.gz-rf-pin-card.is-success .gz-rf-pin-digit:nth-child(3){animation-delay:.10s}.gz-rf-pin-card.is-success .gz-rf-pin-digit:nth-child(4){animation-delay:.15s}.gz-rf-pin-card.is-success .gz-rf-pin-digit:nth-child(5){animation-delay:.20s}.gz-rf-pin-card.is-success .gz-rf-pin-digit:nth-child(6){animation-delay:.25s}
.gz-rf-pin-result.show .gz-rf-result-ring{animation:gzResult .8s cubic-bezier(.2,.9,.2,1) both!important}.gz-rf-pin-result.show h3{animation:gzText .5s .12s both}.gz-rf-pin-result.show p{animation:gzText .5s .2s both}.gz-rf-pin-result.show .gz-rf-result-btn{animation:gzText .5s .28s both}
@keyframes gzBoxLift{0%{transform:translateY(0) rotate(0) scale(1);opacity:.7}35%{transform:translateY(-24px) rotate(-7deg) scale(1.08);box-shadow:0 18px 35px #ff7a0030}70%{transform:translateY(5px) rotate(4deg) scale(.98)}100%{transform:translateY(0) rotate(0) scale(1);opacity:1}}
@keyframes gzDigitsFloat{0%{transform:scale(.96)}45%{transform:scale(1.03) translateY(-4px)}100%{transform:none}}
@keyframes gzOrbit{to{transform:rotate(360deg)}}@keyframes gzRing{0%{transform:scale(.7);opacity:0}35%{opacity:1}100%{transform:scale(1.15);opacity:0}}
@keyframes gzStatus{50%{opacity:.45;transform:translateY(-1px)}}@keyframes gzWrong{20%{transform:translateX(-9px) rotate(-4deg)}40%{transform:translateX(9px) rotate(4deg)}60%{transform:translateX(-6px)}80%{transform:translateX(5px)}100%{transform:none}}
@keyframes gzCorrect{0%{transform:scale(.65) rotate(-15deg);opacity:.2}60%{transform:scale(1.14) rotate(7deg)}100%{transform:none;opacity:1}}
@keyframes gzResult{0%{transform:scale(.25) rotate(-20deg);opacity:0}55%{transform:scale(1.16) rotate(5deg)}100%{transform:none;opacity:1}}@keyframes gzText{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}
@media(max-width:520px){.gz-rf-pin-checking .gz-rf-pin-digit{animation-duration:.65s!important}.gz-rf-pin-checking .gz-rf-pin-icon:before{inset:-13px}.gz-rf-pin-checking .gz-rf-pin-icon:after{inset:-23px}}
@media(prefers-reduced-motion:reduce){.gz-rf-pin-checking .gz-rf-pin-digit,.gz-rf-pin-checking .gz-rf-pin-digits,.gz-rf-pin-checking .gz-rf-pin-icon:before,.gz-rf-pin-checking .gz-rf-pin-icon:after,.gz-rf-pin-checking .gz-rf-pin-status,.gz-rf-pin-result.show .gz-rf-result-ring,.gz-rf-pin-result.show h3,.gz-rf-pin-result.show p,.gz-rf-pin-result.show .gz-rf-result-btn{animation:none!important}}
`;document.head.appendChild(s)})();
(()=>{
  if(document.getElementById('gzForgotPinMotionV1'))return;
  const s=document.createElement('style');s.id='gzForgotPinMotionV1';s.textContent=`
  .gz-forgot-ui{position:relative;overflow:hidden!important;background:linear-gradient(145deg,#fff 0%,#fffaf6 100%)!important;border:1px solid #e7e2dc!important;border-radius:22px!important;padding:26px!important;box-shadow:0 18px 50px rgba(17,17,17,.07)!important;animation:gzForgotIn .62s cubic-bezier(.2,.85,.2,1) both}
  .gz-forgot-ui:before{content:'';position:absolute;width:210px;height:210px;right:-100px;top:-110px;border-radius:50%;background:radial-gradient(circle,#ff6b0030 0,#ff6b000d 42%,transparent 72%);pointer-events:none}
  .gz-forgot-ui:after{content:'';position:absolute;width:150px;height:150px;left:-105px;bottom:-105px;border-radius:50%;background:radial-gradient(circle,#11111110 0,transparent 70%);pointer-events:none}
  .gz-forgot-ui .gz-forgot-icon{position:relative;z-index:1;width:54px;height:54px;border-radius:17px;background:#111;color:#fff;display:grid;place-items:center;font-size:25px;margin-bottom:15px;box-shadow:0 12px 25px rgba(17,17,17,.16);animation:gzForgotIcon .7s .08s cubic-bezier(.2,.9,.2,1) both}
  .gz-forgot-ui .gz-forgot-icon:before{content:'';position:absolute;inset:-7px;border:1px solid #ff6b0030;border-radius:20px;animation:gzForgotRing 1.5s ease-out infinite}
  .gz-forgot-ui h1,.gz-forgot-ui h2,.gz-forgot-ui h3{position:relative;z-index:1}.gz-forgot-ui h1,.gz-forgot-ui h2{letter-spacing:-.035em}.gz-forgot-ui p{position:relative;z-index:1}
  .gz-forgot-steps{position:relative;z-index:1;display:flex;align-items:center;gap:7px;margin:17px 0 15px}.gz-forgot-steps span{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#f1f1ef;color:#777;font:900 10px system-ui;border:1px solid #e2e2df}.gz-forgot-steps span.active{background:#ff6b00;color:#fff;border-color:#ff6b00;box-shadow:0 0 0 5px #ff6b0012}.gz-forgot-steps i{height:1px;flex:0 0 32px;background:#dededb}
  .gz-forgot-meta{position:relative;z-index:1;display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:#fff;border:1px solid #e8e5e1;color:#6d6d6d;font:800 9px system-ui;letter-spacing:.06em;text-transform:uppercase;margin-bottom:10px}.gz-forgot-meta b{color:#ff6b00}
  .gz-forgot-ui input{position:relative;z-index:1!important;border:1.5px solid #dedbd6!important;background:#fff!important;border-radius:14px!important;padding:14px 15px!important;transition:border-color .2s,box-shadow .2s,transform .2s!important}.gz-forgot-ui input:focus{border-color:#ff6b00!important;box-shadow:0 0 0 5px #ff6b0012,0 10px 25px #ff6b0010!important;transform:translateY(-1px)}
  .gz-forgot-ui button{position:relative;z-index:1;transition:transform .2s,box-shadow .2s,background .2s!important}.gz-forgot-ui button:not(.gz-forgot-secondary){background:#111!important;color:#fff!important;border-radius:14px!important;box-shadow:0 10px 22px rgba(17,17,17,.13)}.gz-forgot-ui button:not(.gz-forgot-secondary):hover{transform:translateY(-2px);box-shadow:0 15px 28px rgba(17,17,17,.18)}.gz-forgot-ui .gz-forgot-secondary{background:#fff!important;border:1px solid #ddd!important;color:#111!important;border-radius:14px!important}.gz-forgot-ui .gz-rewards-msg{position:relative;z-index:2}
  @keyframes gzForgotIn{from{opacity:0;transform:translateY(18px) scale(.985)}to{opacity:1;transform:none}}@keyframes gzForgotIcon{from{opacity:0;transform:translateY(16px) rotate(-12deg) scale(.72)}65%{transform:translateY(-3px) rotate(4deg) scale(1.05)}to{opacity:1;transform:none}}@keyframes gzForgotRing{0%{transform:scale(.75);opacity:0}35%{opacity:1}100%{transform:scale(1.12);opacity:0}}
  @media(max-width:600px){.gz-forgot-ui{padding:20px!important;border-radius:18px!important}.gz-forgot-steps i{flex-basis:20px}}@media(prefers-reduced-motion:reduce){.gz-forgot-ui,.gz-forgot-ui .gz-forgot-icon,.gz-forgot-ui .gz-forgot-icon:before{animation:none!important}}
  `;document.head.appendChild(s);
  function decorate(){const root=document.getElementById('gzRewardsApp');if(!root)return;const nodes=[...root.querySelectorAll('h1,h2,h3,p,div')];const heading=nodes.find(el=>/forgot your pin|pin.*forget|pin recovery|forgot.*pin/i.test((el.textContent||'').trim())&&(el.textContent||'').trim().length<80);if(!heading)return;let box=heading;for(let i=0;i<7&&box;i++,box=box.parentElement){if(box.querySelector?.('input')&&box.querySelector?.('button'))break}if(!box||!box.querySelector?.('input')||!box.querySelector?.('button'))return;if(box.dataset.gzForgotDecorated)return;box.dataset.gzForgotDecorated='1';box.classList.add('gz-forgot-ui');const icon=document.createElement('div');icon.className='gz-forgot-icon';icon.textContent='🔐';box.insertBefore(icon,box.firstChild);const meta=document.createElement('div');meta.className='gz-forgot-meta';meta.innerHTML='<b>SECURE RECOVERY</b><span>EMAIL ONLY • ONE-TIME CODE</span>';box.insertBefore(meta,heading);const steps=document.createElement('div');steps.className='gz-forgot-steps';steps.innerHTML='<span class="active">1</span><i></i><span>2</span><i></i><span>3</span>';box.insertBefore(steps,heading);box.querySelectorAll('button').forEach(btn=>{if(/back to login/i.test(btn.textContent||''))btn.classList.add('gz-forgot-secondary')})}
  const run=()=>requestAnimationFrame(decorate);run();new MutationObserver(run).observe(document.getElementById('gzRewardsApp')||document.body,{childList:true,subtree:true});
})();