(()=>{'use strict';
const C=window.GRABZONE_CONFIG||{},base=String(C.backendUrl||'').replace(/\/$/,'');const key='gz_vendor_token';
const get=()=>{try{return localStorage.getItem(key)||''}catch{return''}},set=t=>{try{t?localStorage.setItem(key,t):localStorage.removeItem(key)}catch{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>'৳'+Number(v||0).toLocaleString('en-BD');
async function api(path,opts={}){const h=new Headers(opts.headers||{});h.set('Content-Type','application/json');const t=get();if(t)h.set('Authorization','Bearer '+t);const r=await fetch(base+path,{...opts,headers:h,cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Request failed.');return b}
function notice(t){const e=document.getElementById('vpMsg');if(e)e.textContent=t}
async function login(e){e.preventDefault();try{const email=document.getElementById('vpEmail').value.trim(),password=document.getElementById('vpPassword').value;const b=await fetch(base+'/api/marketplace/vendor-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const x=await b.json();if(!b.ok)throw new Error(x.error||'Login failed.');set(x.token);document.getElementById('vpLogin').classList.add('hidden');document.getElementById('vpApp').classList.remove('hidden');document.getElementById('vpVendorName').textContent=x.vendor.name;load('overview')}catch(err){notice('✕ '+err.message)}}
async function load(tab){const m=document.getElementById('vpMain');m.innerHTML='<div class="vp-panel">Loading…</div>';try{
 if(tab==='overview'){const x=await api('/api/marketplace/vendor?action=overview');m.innerHTML='<div class="vp-kpis">'+[['Products',x.products],['Orders',x.orders],['Shipments',x.shipments]].map(a=>'<div class="vp-kpi"><span>'+a[0]+'</span><strong>'+Number(a[1]||0).toLocaleString()+'</strong></div>').join('')+'</div><div class="vp-panel"><h2>Vendor workspace</h2><p>Your account is isolated to this vendor. Main GrabZone admin retains marketplace-wide control.</p></div>';return}
 if(tab==='products'){const x=await api('/api/marketplace/vendor?action=products');m.innerHTML='<div class="vp-panel"><div class="vp-panel-head"><div><h2>Your products</h2><p>Manage publication and featured status.</p></div><button id="vpAddProduct">Add product</button></div><div class="vp-table-wrap"><table class="vp-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Published</th><th>Featured</th><th>Action</th></tr></thead><tbody>'+x.products.map(p=>'<tr><td><b>'+esc(p.name)+'</b></td><td>'+esc(p.category)+'</td><td>'+money(p.price)+'</td><td>'+(Number(p.published)?'Yes':'No')+'</td><td>'+(Number(p.vendor_featured)?'Yes':'No')+'</td><td><button class="vp-small" data-edit="'+esc(p.id)+'">Edit</button></td></tr>').join('')+'</tbody></table></div></div>';
 document.querySelectorAll('[data-edit]').forEach(btn=>btn.onclick=async()=>{const p=x.products.find(z=>String(z.id)===btn.dataset.edit);if(!p)return;const price=prompt('Price',p.price);if(price===null)return;const published=confirm('Publish this product?');const featured=confirm('Feature this product?');try{await api('/api/marketplace/vendor?action=update_product',{method:'POST',body:JSON.stringify({id:p.id,price:Number(price),published, vendor_featured:featured})});load('products')}catch(e){notice('✕ '+e.message)}});
 document.getElementById('vpAddProduct').onclick=()=>notice('Product creation will use the vendor product uploader in the next marketplace module.');return}
 if(tab==='orders'){const x=await api('/api/marketplace/vendor?action=orders');m.innerHTML='<div class="vp-panel"><h2>Your orders</h2><div class="vp-table-wrap"><table class="vp-table"><thead><tr><th>Order</th><th>Customer</th><th>Subtotal</th><th>Shipping</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>'+x.orders.map(o=>'<tr><td><b>'+esc(o.order_number)+'</b><br><small>'+esc(o.public_tracking_id)+'</small></td><td>'+esc(o.customer_name)+'<br>'+esc(o.phone)+'</td><td>'+money(o.subtotal)+'</td><td>'+money(o.shipping_charge)+'</td><td><b>'+money(o.total)+'</b></td><td>'+esc(o.status)+'</td><td><button class="vp-small" data-order="'+esc(o.id)+'">Update</button></td></tr>').join('')+'</tbody></table></div></div>';document.querySelectorAll('[data-order]').forEach(btn=>btn.onclick=async()=>{const o=x.orders.find(z=>String(z.id)===btn.dataset.order);if(!o)return;const status=prompt('Status: New / Contacting / Confirmed / Processing / Shipped / Delivered / Cancelled',o.status);if(!status)return;await api('/api/marketplace/vendor?action=update_order',{method:'POST',body:JSON.stringify({id:o.id,status})});load('orders')});return}
 if(tab==='shipments'){const x=await api('/api/marketplace/vendor?action=shipments');const orders=(await api('/api/marketplace/vendor?action=orders')).orders||[];m.innerHTML='<div class="vp-panel"><div class="vp-panel-head"><div><h2>Shipments</h2><p>Create seller-specific tracking for customer orders.</p></div><button id="vpCreateShipment">Create shipment</button></div><div class="vp-table-wrap"><table class="vp-table"><thead><tr><th>Shipment</th><th>Order</th><th>Courier</th><th>Tracking</th><th>Status</th></tr></thead><tbody>'+x.shipments.map(s=>'<tr><td><b>'+esc(s.shipment_tracking_id)+'</b></td><td>'+esc(s.order_number)+'</td><td>'+esc(s.courier_name||'—')+'</td><td>'+esc(s.courier_tracking_number||'—')+'</td><td>'+esc(s.status)+'</td></tr>').join('')+'</tbody></table></div></div>';document.getElementById('vpCreateShipment').onclick=async()=>{const o=orders.find(z=>!x.shipments.some(s=>s.vendor_order_id===z.id));if(!o)return notice('No unshipped vendor order found.');const courier=prompt('Courier name','Pathao');const tracking=prompt('Courier tracking number','');const url=prompt('Courier tracking URL','');await api('/api/marketplace/vendor?action=create_shipment',{method:'POST',body:JSON.stringify({vendor_order_id:o.id,courier_name:courier,courier_tracking_number:tracking,courier_tracking_url:url,status:'Processing'})});load('shipments')};return}
 if(tab==='store'){const x=await api('/api/marketplace/vendor?action=store'),v=x.vendor||{},s=x.settings||{},sh=x.shipping||{};m.innerHTML='<div class="vp-panel"><h2>Storefront settings</h2><form id="vpStore" class="vp-form"><label>Tagline<input name="tagline" value="'+esc(v.tagline||'')+'"></label><label>Accent color<input name="accent_color" value="'+esc(v.accent_color||'#ff6a00')+'"></label><label class="full">Description<textarea name="description">'+esc(v.description||'')+'</textarea></label><label>Hero title<input name="hero_title" value="'+esc(s.hero_title||'')+'"></label><label>Hero description<input name="hero_description" value="'+esc(s.hero_description||'')+'"></label><label class="full">Announcement<textarea name="announcement">'+esc(s.announcement||'')+'</textarea></label><label>Shipping fee<input name="shipping_fee" type="number" min="0" value="'+Number(sh.shipping_fee||0)+'"></label><label>Shipping enabled<input name="shipping_enabled" type="checkbox" '+(Number(sh.enabled??1)?'checked':'')+'></label><div class="full"><button>Save storefront</button></div></form></div>';document.getElementById('vpStore').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),b=Object.fromEntries(fd.entries());b.shipping_enabled=e.target.shipping_enabled.checked;try{await api('/api/marketplace/vendor?action=update_store',{method:'POST',body:JSON.stringify(b)});await api('/api/marketplace/vendor?action=update_shipping',{method:'POST',body:JSON.stringify({shipping_fee:b.shipping_fee,enabled:b.shipping_enabled})});notice('✓ Storefront saved.');}catch(err){notice('✕ '+err.message)}};return}
 }catch(e){m.innerHTML='<div class="vp-panel">✕ '+esc(e.message)+'</div>'}}
document.getElementById('vpLoginForm').onsubmit=login;document.getElementById('vpLogout').onclick=()=>{set('');location.reload()};document.querySelectorAll('#vpApp nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#vpApp nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');load(b.dataset.tab)});if(get()){document.getElementById('vpLogin').classList.add('hidden');document.getElementById('vpApp').classList.remove('hidden');api('/api/marketplace/vendor?action=overview').then(()=>load('overview')).catch(()=>{set('');location.reload()})}})();
