/* GRABZONE PAYMENT CONTROL — FINAL
   Load AFTER admin.js in admin.html.
   Stores payment methods inside site_settings.payment_methods.
   Every method supports separate Bangla + English text, logo URL,
   visibility and ordering. */
(() => {
  'use strict';
  const DEFAULTS = [
    {id:'bkash',name_bn:'bKash পেমেন্ট',name_en:'bKash Payment',description_bn:'যোগ্য অর্ডারের জন্য bKash পেমেন্ট করা যাবে। অর্ডার কনফার্ম হলে আমাদের টিম বর্তমান পেমেন্ট নির্দেশনা দেবে।',description_en:'bKash payment is available for eligible orders. Our team will provide the current payment instructions after order confirmation.',note_bn:'পেমেন্ট পাঠানোর আগে GrabZone টিমের কাছ থেকে bKash নম্বর নিশ্চিত করুন।',note_en:'Always confirm the bKash number with the GrabZone team before sending payment.',logo_url:'',enabled:true,sort_order:1},
    {id:'cod',name_bn:'ক্যাশ অন ডেলিভারি',name_en:'Cash on Delivery',description_bn:'আপনার লোকেশন ও অর্ডারের জন্য সুবিধাটি উপলভ্য থাকলে পণ্য হাতে পাওয়ার সময় পণ্যের বাকি টাকা পরিশোধ করতে পারবেন।',description_en:'If available for your location and order, you can pay the remaining product amount when the order is delivered.',note_bn:'ডেলিভারি চার্জ আগে পরিশোধ করতে হবে। বাকি পণ্যের মূল্য ডেলিভারির সময় পরিশোধ করা যাবে।',note_en:'Delivery charge must be paid in advance. The remaining product amount can be paid on delivery.',logo_url:'',enabled:true,sort_order:2}
  ];
  const C=window.GRABZONE_CONFIG||{};
  const sb=window.grabzoneD1||null;
  let methods=DEFAULTS.map(x=>({...x}));
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const clone=x=>JSON.parse(JSON.stringify(x));
  function normalize(list){return (Array.isArray(list)?list:[]).map((m,i)=>({id:String(m.id||`payment_${Date.now()}_${i}`),name_bn:String(m.name_bn??m.name??''),name_en:String(m.name_en??m.name??''),description_bn:String(m.description_bn??m.description??''),description_en:String(m.description_en??m.description??''),note_bn:String(m.note_bn??m.note??''),note_en:String(m.note_en??m.note??''),logo_url:String(m.logo_url??''),enabled:m.enabled!==false,sort_order:Number(m.sort_order??i+1)})).sort((a,b)=>a.sort_order-b.sort_order)}
  function style(){if(document.getElementById('gzPaymentAdminCSS'))return;const s=document.createElement('style');s.id='gzPaymentAdminCSS';s.textContent=`#tab-payment .gz-p-list{display:grid;gap:18px}.gz-p-card{background:var(--card,#fff);border:1px solid #e4e4e4;border-radius:20px;padding:20px}.gz-p-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:16px}.gz-p-actions{display:flex;gap:7px;flex-wrap:wrap}.gz-p-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.gz-p-grid label{display:grid;gap:7px;font-size:12px;font-weight:700}.gz-p-grid input,.gz-p-grid textarea{box-sizing:border-box;width:100%;padding:11px 12px;border:1px solid #ddd;border-radius:11px;background:#fff;color:#111;font:inherit}.gz-p-grid textarea{min-height:92px;resize:vertical}.gz-p-full{grid-column:1/-1}.gz-p-preview{width:54px;height:54px;border:1px solid #eee;border-radius:14px;object-fit:contain;background:#fafafa}.gz-p-status{font-size:12px;color:#666}.gz-p-switch{display:flex!important;align-items:center;grid-template-columns:auto 1fr!important;gap:8px!important}.gz-p-switch input{width:auto!important}@media(max-width:760px){.gz-p-grid{grid-template-columns:1fr}.gz-p-full{grid-column:auto}}`;document.head.appendChild(s)}
  function makeNav(){const sidebar=document.querySelector('.sidebar');if(!sidebar||document.getElementById('gzPaymentNav')||sidebar.querySelector('[data-tab="payment"]'))return;const b=document.createElement('button');b.id='gzPaymentNav';b.type='button';b.className='side-link';b.dataset.tab='payment';b.innerHTML='▣ <span>Payment Methods</span>';const policy=sidebar.querySelector('a[href="policy-admin.html"]');policy?sidebar.insertBefore(b,policy):sidebar.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setTimeout(openTab,0)})}
  function makeTab(){if(document.getElementById('tab-payment'))return;const main=document.querySelector('main.content');if(!main)return;const sec=document.createElement('section');sec.id='tab-payment';sec.className='tab';sec.innerHTML=`<div class="page-title"><div><div class="eyebrow">PAYMENT CONTROL</div><h1>Payment Methods</h1><p>Control payment methods, Bangla/English text, logos and visibility from the admin panel.</p></div><div class="gz-p-actions"><button class="primary" id="gzPSave" type="button">Save payment methods</button><button class="ghost" id="gzPAdd" type="button">＋ Add method</button></div></div><div class="panel"><div id="gzPStatus" class="gz-p-status">Loading payment methods…</div></div><div id="gzPList" class="gz-p-list"></div>`;main.appendChild(sec);document.getElementById('gzPSave').onclick=save;document.getElementById('gzPAdd').onclick=()=>{methods.push({id:`payment_${Date.now()}`,name_bn:'নতুন পেমেন্ট মেথড',name_en:'New Payment Method',description_bn:'',description_en:'',note_bn:'',note_en:'',logo_url:'',enabled:true,sort_order:methods.length+1});render()}}
  function openTab(){const tabs=document.querySelectorAll('main.content .tab');tabs.forEach(x=>x.classList.remove('active'));document.querySelectorAll('.sidebar .side-link').forEach(x=>x.classList.remove('active'));document.getElementById('tab-payment')?.classList.add('active');document.getElementById('gzPaymentNav')?.classList.add('active');render();}
  function render(){const list=document.getElementById('gzPList');if(!list)return;list.innerHTML=methods.map((m,i)=>`<div class="gz-p-card" data-i="${i}"><div class="gz-p-head"><strong>${esc(m.name_en||m.name_bn||'Payment Method')}</strong><div class="gz-p-actions"><button class="ghost up" type="button" ${i===0?'disabled':''}>↑</button><button class="ghost down" type="button" ${i===methods.length-1?'disabled':''}>↓</button><button class="ghost del" type="button">Delete</button></div></div><div class="gz-p-grid"><label>Bangla name<input data-f="name_bn" value="${esc(m.name_bn)}"></label><label>English name<input data-f="name_en" value="${esc(m.name_en)}"></label><label class="gz-p-full">Bangla description<textarea data-f="description_bn">${esc(m.description_bn)}</textarea></label><label class="gz-p-full">English description<textarea data-f="description_en">${esc(m.description_en)}</textarea></label><label class="gz-p-full">Bangla payment note / instruction<textarea data-f="note_bn">${esc(m.note_bn)}</textarea></label><label class="gz-p-full">English payment note / instruction<textarea data-f="note_en">${esc(m.note_en)}</textarea></label><label>Logo URL<input data-f="logo_url" value="${esc(m.logo_url)}" placeholder="https://.../logo.png"></label><label>Sort order<input data-f="sort_order" type="number" value="${Number(m.sort_order||i+1)}"></label><label class="gz-p-switch"><input data-f="enabled" type="checkbox" ${m.enabled?'checked':''}> Show on website</label><div>${m.logo_url?`<img class="gz-p-preview" src="${esc(m.logo_url)}" alt="">`:'<span class="gz-p-status">No logo set</span>'}</div></div></div>`).join('');list.querySelectorAll('.gz-p-card').forEach(card=>{const i=Number(card.dataset.i);card.querySelectorAll('[data-f]').forEach(el=>el.addEventListener('input',()=>read(card,i)));card.querySelectorAll('[data-f]').forEach(el=>el.addEventListener('change',()=>read(card,i)));card.querySelector('.del').onclick=()=>{methods.splice(i,1);methods.forEach((x,n)=>x.sort_order=n+1);render()};card.querySelector('.up').onclick=()=>{if(i<1)return;[methods[i-1],methods[i]]=[methods[i],methods[i-1]];methods.forEach((x,n)=>x.sort_order=n+1);render()};card.querySelector('.down').onclick=()=>{if(i>=methods.length-1)return;[methods[i+1],methods[i]]=[methods[i],methods[i+1]];methods.forEach((x,n)=>x.sort_order=n+1);render()}})}
  function read(card,i){const m=methods[i];if(!m)return;card.querySelectorAll('[data-f]').forEach(el=>{const f=el.dataset.f;m[f]=el.type==='checkbox'?el.checked:f==='sort_order'?Number(el.value||0):el.value})}
  async function load(){const st=document.getElementById('gzPStatus');if(!st)return;if(!sb){st.textContent='Database service is not configured.';return}st.textContent='Loading…';const {data,error}=await sb.from('site_settings').select('payment_methods').eq('id',1).maybeSingle();if(error){console.error(error);st.textContent='Could not load payment methods.';return}methods=normalize(data?.payment_methods?.length?data.payment_methods:DEFAULTS);st.textContent=`${methods.length} payment method(s).`;render()}
  async function save(){const st=document.getElementById('gzPStatus');if(!st||!sb)return;document.querySelectorAll('#gzPList .gz-p-card').forEach((c,i)=>read(c,i));methods=normalize(methods);st.textContent='Saving…';const {error}=await sb.from('site_settings').update({payment_methods:methods}).eq('id',1);if(error){console.error(error);st.textContent='Save failed: '+error.message;return}st.textContent='Saved successfully. Refresh the storefront to see the changes.'}
  function boot(){style();makeNav();makeTab();const staticNav=document.querySelector('.sidebar [data-tab="payment"]');if(staticNav&&!staticNav.dataset.gzPaymentBound){staticNav.dataset.gzPaymentBound='1';staticNav.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setTimeout(openTab,0)})}load()}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();
