(() => {
'use strict';
const D1=window.grabzoneD1||null, KEY='gz_rewards_token';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const token=()=>{try{return localStorage.getItem(KEY)||''}catch{return''}};
const setToken=v=>{try{if(v)localStorage.setItem(KEY,v);else localStorage.removeItem(KEY)}catch{}};
async function rpc(fn,args){if(!D1)throw Error('Rewards service is not configured.');const r=await D1.rpc(fn,args||{});if(r.error)throw Error(r.error.message||'Rewards request failed.');return r.data}
function css(){if($('gzRewardsStyle'))return;const s=document.createElement('style');s.id='gzRewardsStyle';s.textContent='.gz-rewards-link{border:1px solid #ddd;background:#fff;color:#111;border-radius:999px;padding:9px 13px;font:800 12px system-ui;cursor:pointer}.gz-rewards-modal{position:fixed;inset:0;z-index:100050;display:none;align-items:center;justify-content:center;padding:18px;background:#0009;backdrop-filter:blur(6px)}.gz-rewards-modal.open{display:flex}.gz-rewards-card{width:min(520px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:24px;box-shadow:0 30px 100px #0005;position:relative}.gz-rewards-close{position:absolute;right:14px;top:14px;border:0;background:#f1f1ef;border-radius:50%;width:36px;height:36px;font-size:21px;cursor:pointer}.gz-rewards-card h2{margin:4px 42px 6px 0;font-size:27px}.gz-rewards-card p{color:#777;font-size:13px;line-height:1.5}.gz-rewards-grid{display:grid;gap:10px;margin-top:16px}.gz-rewards-grid input{width:100%;box-sizing:border-box;border:1px solid #ddd;border-radius:11px;padding:12px;font:inherit}.gz-rewards-btn{width:100%;border:0;background:#111;color:#fff;border-radius:11px;padding:13px;font-weight:900;cursor:pointer}.gz-rewards-btn.alt{background:#fff;color:#111;border:1px solid #ddd}.gz-rewards-msg{min-height:20px;margin-top:9px;font-size:12px;font-weight:800}.gz-rewards-stat{padding:15px;border:1px solid #e7e7e3;border-radius:16px;background:#fafaf8}.gz-rewards-stat b{display:block;font-size:25px;margin-top:4px}.gz-rewards-tier{display:inline-flex;padding:6px 10px;border-radius:999px;background:#111;color:#fff;font-size:10px;font-weight:900}.gz-rewards-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.gz-rewards-history{display:grid;gap:8px;margin-top:14px}.gz-rewards-row{display:flex;justify-content:space-between;gap:12px;padding:11px;border:1px solid #eee;border-radius:12px}.gz-rewards-row small{display:block;color:#777;margin-top:3px}@media(max-width:600px){.gz-rewards-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function ensure(){css();if($('gzRewardsModal'))return;const header=document.querySelector('.header');if(header&&!$('gzRewardsNav')){const a=header.querySelector('.header-actions')||header,b=document.createElement('button');b.id='gzRewardsNav';b.className='gz-rewards-link';b.type='button';b.textContent='🎁 Rewards';b.onclick=open;a.appendChild(b)}const m=document.createElement('div');m.id='gzRewardsModal';m.className='gz-rewards-modal';m.innerHTML='<div class="gz-rewards-card"><button class="gz-rewards-close" type="button">×</button><div id="gzRewardsBody"></div></div>';document.body.appendChild(m);m.querySelector('.gz-rewards-close').onclick=close;m.onclick=e=>{if(e.target===m)close()}}
function open(){ensure();$('gzRewardsModal').classList.add('open');document.body.style.overflow='hidden';render()}
function close(){$('gzRewardsModal')?.classList.remove('open');document.body.style.overflow=''}
function showAuth(mode){const b=$('gzRewardsBody');b.innerHTML=mode==='register' ? '<div class="eyebrow">GRABZONE REWARDS</div><h2>Join Rewards</h2><p>Create one optional Rewards account. You can still shop as a guest.</p><div class="gz-rewards-grid"><input id="grName" placeholder="Full name"><input id="grPhone" placeholder="01XXXXXXXXX" inputmode="numeric" maxlength="11"><input id="grEmail" type="email" placeholder="Email address"><input id="grPin" type="password" inputmode="numeric" maxlength="6" placeholder="Create 4–6 digit PIN"><input id="grPin2" type="password" inputmode="numeric" maxlength="6" placeholder="Confirm PIN"><button class="gz-rewards-btn" id="grRegister">Create Rewards Account</button></div><div id="grMsg" class="gz-rewards-msg"></div><button class="gz-rewards-btn alt" id="grToLogin">Already a member? Login</button>' : '<div class="eyebrow">GRABZONE REWARDS</div><h2>Welcome back</h2><p>Use your Rewards phone/email and PIN.</p><div class="gz-rewards-grid"><input id="grLoginId" placeholder="Phone or email"><input id="grLoginPin" type="password" inputmode="numeric" maxlength="6" placeholder="Rewards PIN"><button class="gz-rewards-btn" id="grLogin">Login</button></div><div id="grMsg" class="gz-rewards-msg"></div><div class="gz-rewards-actions"><button class="gz-rewards-btn alt" id="grToRegister">Join Rewards</button><button class="gz-rewards-btn alt" id="grForgot">Forgot PIN?</button></div>';if($('grRegister'))$('grRegister').onclick=register;if($('grToLogin'))$('grToLogin').onclick=()=>showAuth('login');if($('grLogin'))$('grLogin').onclick=login;if($('grToRegister'))$('grToRegister').onclick=()=>showAuth('register');if($('grForgot'))$('grForgot').onclick=forgot}
async function register(){const m=$('grMsg');try{const d=await rpc('rewards_register',{p_name:$('grName').value.trim(),p_phone:$('grPhone').value.replace(/\D/g,''),p_email:$('grEmail').value.trim(),p_pin:$('grPin').value,p_pin_confirm:$('grPin2').value});setToken(d.token);loadDashboard()}catch(e){m.textContent='✕ '+e.message;m.style.color='#b42318'}}
async function login(){const m=$('grMsg');try{const d=await rpc('rewards_login',{p_identifier:$('grLoginId').value.trim(),p_pin:$('grLoginPin').value});setToken(d.token);loadDashboard()}catch(e){m.textContent='✕ '+e.message;m.style.color='#b42318'}}
async function forgot(){const b=$('gzRewardsBody');b.innerHTML='<div class="eyebrow">PIN RECOVERY</div><h2>Forgot your PIN?</h2><p>Enter the email attached to your Rewards account. A verification code will be sent only to that email.</p><div class="gz-rewards-grid"><input id="grResetEmail" type="email" placeholder="Registered Rewards email"><button class="gz-rewards-btn" id="grSendCode">Send Verification Code</button></div><div id="grMsg" class="gz-rewards-msg"></div><button class="gz-rewards-btn alt" id="grBackLogin">Back to Login</button>';$('grSendCode').onclick=sendCode;$('grBackLogin').onclick=()=>showAuth('login')}
async function sendCode(){const m=$('grMsg'),email=$('grResetEmail').value.trim();try{await rpc('rewards_forgot_pin',{p_email:email});showVerify(email)}catch(e){m.textContent='✕ '+e.message;m.style.color='#b42318'}}
function showVerify(email){const b=$('gzRewardsBody');b.innerHTML='<div class="eyebrow">EMAIL VERIFICATION</div><h2>Check your email</h2><p>Enter the 6-digit code sent to <b>'+esc(email)+'</b>.</p><div class="gz-rewards-grid"><input id="grOtp" inputmode="numeric" maxlength="6" placeholder="6-digit code"><button class="gz-rewards-btn" id="grVerify">Verify Code</button></div><div id="grMsg" class="gz-rewards-msg"></div>';$('grVerify').onclick=()=>verifyCode(email)}
async function verifyCode(email){const m=$('grMsg');try{const d=await rpc('rewards_verify_reset',{p_email:email,p_code:$('grOtp').value.trim()});showReset(d.reset_token)}catch(e){m.textContent='✕ '+e.message;m.style.color='#b42318'}}
function showReset(t){const b=$('gzRewardsBody');b.innerHTML='<div class="eyebrow">RESET PIN</div><h2>Create a new PIN</h2><div class="gz-rewards-grid"><input id="grNewPin" type="password" inputmode="numeric" maxlength="6" placeholder="New 4–6 digit PIN"><input id="grNewPin2" type="password" inputmode="numeric" maxlength="6" placeholder="Confirm new PIN"><button class="gz-rewards-btn" id="grReset">Reset PIN</button></div><div id="grMsg" class="gz-rewards-msg"></div>';$('grReset').onclick=async()=>{const m=$('grMsg');try{await rpc('rewards_reset_pin',{p_reset_token:t,p_pin:$('grNewPin').value,p_pin_confirm:$('grNewPin2').value});showAuth('login')}catch(e){m.textContent='✕ '+e.message;m.style.color='#b42318'}}}
async function loadDashboard(){const b=$('gzRewardsBody');try{const d=await rpc('rewards_me',{p_token:token()});b.innerHTML='<div class="eyebrow">GRABZONE REWARDS</div><h2>Welcome, '+esc(d.name)+' 👋</h2><span class="gz-rewards-tier">'+esc(d.tier)+' MEMBER</span><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px"><div class="gz-rewards-stat"><small>Available GP</small><b>'+Number(d.points).toLocaleString('en-BD')+'</b><span>≈ ৳'+Number(d.value).toLocaleString('en-BD')+'</span></div><div class="gz-rewards-stat"><small>12-Month Earned</small><b>'+Number(d.twelve_month_earned).toLocaleString('en-BD')+'</b><span>'+esc(d.next_tier_label)+'</span></div></div><p style="margin-top:14px"><b>'+Number(d.next_tier_remaining).toLocaleString('en-BD')+' GP</b> to next tier</p><div class="gz-rewards-grid" style="margin-top:14px"><input id="grRedeemPoints" type="number" min="10" step="10" placeholder="Points to redeem"><input id="grRedeemPin" type="password" inputmode="numeric" maxlength="6" placeholder="Rewards PIN"><button class="gz-rewards-btn" id="grRedeem">Redeem Points</button></div><div id="grRedeemMsg" class="gz-rewards-msg"></div><div class="gz-rewards-actions"><button class="gz-rewards-btn alt" id="grHistory">History</button><button class="gz-rewards-btn alt" id="grLogout">Logout</button></div><div id="grHistoryBox"></div>';$('grHistory').onclick=history;$('grRedeem').onclick=redeem;$('grLogout').onclick=()=>{setToken('');showAuth('login')}}catch(e){setToken('');showAuth('login')}}
async function redeem(){const m=$('grRedeemMsg'),pts=Math.floor(Number($('grRedeemPoints').value||0)),pin=$('grRedeemPin').value;if(!pts){m.textContent='Enter points to redeem.';return}try{const d=await rpc('rewards_redeem',{p_token:token(),p_points:pts,p_pin:pin});m.textContent='✓ Redeemed '+d.points_redeemed+' GP. New balance: '+d.balance+' GP. Reference: '+d.reference;loadDashboard()}catch(e){m.textContent='✕ '+e.message;m.style.color='#b42318'}}
async function history(){const box=$('grHistoryBox');box.innerHTML='<div class="gz-rewards-msg">Loading…</div>';try{const d=await rpc('rewards_history',{p_token:token()});const rows=Array.isArray(d)?d:[];box.innerHTML='<div class="gz-rewards-history">'+rows.map(x=>'<div class="gz-rewards-row"><div><b>'+esc(x.type)+'</b><small>'+esc(x.reference||'')+' · '+new Date(x.created_at).toLocaleString()+'</small></div><strong>'+((Number(x.points)>0?'+':'')+Number(x.points))+' GP</strong></div>').join('')+'</div>'}catch(e){box.textContent=e.message}}
function render(){if(token())loadDashboard();else showAuth('login')}
window.GrabZoneRewards={open,close,render,token};
document.addEventListener('DOMContentLoaded',ensure);
})();