let sb=null, allProducts=[], activeCategory="All";
const C=window.GRABZONE_CONFIG;
if(C && !C.supabaseUrl.includes("PASTE_") && window.supabase) sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
function dmLink(t){return (C.whatsapp||"")+"?text="+encodeURIComponent(t)}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function escAttr(x){return esc(x).replace(/`/g,"&#96;")}
async function load(){applyCommon(); if(!sb){showError("Supabase is not configured yet.");return} await Promise.all([loadProducts(),loadNotices()]); renderDetail()}
function applyCommon(){document.getElementById("year")?.textContent=new Date().getFullYear(); for(const [id,url] of [["headerDm",C.whatsapp],["wa",C.whatsapp],["ig",C.instagram],["ms",C.messenger]]){const e=document.getElementById(id);if(e)e.href=url||"#"}const r=document.getElementById("refDm");if(r)r.href=dmLink("I have a referral code. Please verify it and tell me my eligible coupon.")}
function showError(t){const e=document.getElementById("products");if(e)e.innerHTML=`<div class="empty">${esc(t)}</div>`}
async function loadProducts(){const {data,error}=await sb.from("products").select("*").eq("published",true).order("created_at",{ascending:false});if(error){showError(error.message);return}allProducts=data||[];renderProducts()}
function renderProducts(){const grid=document.getElementById("products");if(!grid)return;const q=(document.getElementById("search")?.value||"").toLowerCase();const filtered=allProducts.filter(p=>(activeCategory==="All"||p.category===activeCategory)&&`${p.name} ${p.category} ${p.description||""}`.toLowerCase().includes(q));grid.innerHTML=filtered.map(card).join("");document.getElementById("empty")?.classList.toggle("hidden",filtered.length>0);renderCategories()}
function renderCategories(){const e=document.getElementById("categories");if(!e)return;const cats=["All",...new Set(allProducts.map(p=>p.category).filter(Boolean))];e.innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?"active":""}" onclick="activeCategory=${JSON.stringify(c)};renderProducts()">${esc(c)}</button>`).join("")}
function card(p){return `<a class="product-card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-image"><img src="${escAttr(p.image_url)}" alt="${escAttr(p.name)}" loading="lazy"></div><div class="product-info">${p.tag?`<span class="tag">${esc(p.tag)}</span>`:""}<div class="product-cat">${esc(p.category)}</div><div class="product-name">${esc(p.name)}</div><div><span class="price">${esc(C.currency)}${Number(p.price).toLocaleString()}</span>${p.old_price?`<span class="old">${esc(C.currency)}${Number(p.old_price).toLocaleString()}</span>`:""}</div></div></a>`}
async function loadNotices(){const e=document.getElementById("noticeTrack");if(!e)return;const {data,error}=await sb.from("notices").select("*").eq("active",true).order("sort_order",{ascending:true});if(error){e.textContent="";return}e.innerHTML=(data?.length?data:[{title:"Welcome",message:"Shop our latest products and message us to order."}]).map(n=>`<span class="notice-item"><b>${esc(n.title)}</b>${esc(n.message)}</span>`).join("")}
async function renderDetail(){const el=document.getElementById("productDetail");if(!el||!sb)return;const id=new URLSearchParams(location.search).get("id");if(!id)return;const {data:p,error}=await sb.from("products").select("*").eq("id",id).eq("published",true).maybeSingle();if(error||!p){el.innerHTML="<h1>Product not found</h1>";return}document.title=p.name+" — GRABZONE";el.innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${escAttr(p.image_url)}" alt="${escAttr(p.name)}"></div><div><div class="eyebrow">${esc(p.category)}</div><h1>${esc(p.name)}</h1>${p.tag?`<span class="tag">${esc(p.tag)}</span>`:""}<div class="detail-price">${esc(C.currency)}${Number(p.price).toLocaleString()} ${p.old_price?`<span class="old">${esc(C.currency)}${Number(p.old_price).toLocaleString()}</span>`:""}</div><p class="detail-desc">${esc(p.description||"")}</p><div class="dm-box"><strong>Have a referral code?</strong><p>Enter it below so our team can verify it and apply an eligible coupon.</p><input id="refCode" placeholder="Optional referral code"><a class="btn btn-dark btn-full" target="_blank" id="orderBtn">DM to Order</a></div></div></div>`;const btn=document.getElementById("orderBtn");btn.href=dmLink(`I want to order: ${p.name} | Price: ${C.currency}${p.price}`);document.getElementById("refCode").addEventListener("input",e=>btn.href=dmLink(`I want to order: ${p.name} | Price: ${C.currency}${p.price}${e.target.value.trim()?" | Referral code: "+e.target.value.trim():""}`))}
document.addEventListener("DOMContentLoaded",load);