let sb=null, allProducts=[], activeCategory="All", SITE={};
const C=window.GRABZONE_CONFIG;
if(C&&!C.supabaseUrl.includes("PASTE_")&&window.supabase)sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function escAttr(x){return esc(x).replace(/`/g,"&#96;")}
function dmLink(t){const base=SITE.whatsapp||C.whatsapp||"";return base?base+"?text="+encodeURIComponent(t):"#"}
async function load(){if(!sb){showError("Supabase is not configured yet.");return}await loadSettings();applySiteSettings();await Promise.all([loadProducts(),loadNotices()]);renderDetail()}
async function loadSettings(){const{data,error}=await sb.from("site_settings").select("*").eq("id",1).maybeSingle();if(error){console.error(error);return}if(data)SITE=data}
function setText(id,v){const e=document.getElementById(id);if(e&&v!==undefined&&v!==null)e.textContent=v}
function setHref(id,v){const e=document.getElementById(id);if(e&&v)e.href=v}
function applySiteSettings(){
 const name=SITE.store_name||C.storeName||"GRABZONE";document.title=name;
 setText("storeName",name);setText("footerName",name);setText("heroBrand",name);
 setText("heroEyebrow",SITE.hero_eyebrow);setText("heroTitle",SITE.hero_title);setText("heroTitleEm",SITE.hero_title_em);setText("heroDescription",SITE.hero_description);
 setText("offerTitle",SITE.offer_title);setText("offerMessage",SITE.offer_message);setText("offerCode",SITE.offer_code);
 setText("collectionEyebrow",SITE.collection_eyebrow);setText("collectionTitle",SITE.collection_title);
 setText("howEyebrow",SITE.how_eyebrow);setText("howTitle",SITE.how_title);setText("step1Title",SITE.step1_title);setText("step1Body",SITE.step1_body);setText("step2Title",SITE.step2_title);setText("step2Body",SITE.step2_body);setText("step3Title",SITE.step3_title);setText("step3Body",SITE.step3_body);
 setText("referralEyebrow",SITE.referral_eyebrow);setText("referralTitle",SITE.referral_title);setText("referralBody",SITE.referral_body);
 setText("refDm",SITE.referral_button_text);setText("footerText",SITE.footer_text||("© "+name+" . All rights reserved."));
 setText("nav1",SITE.header_link1_label);setText("nav2",SITE.header_link2_label);setText("nav3",SITE.header_link3_label);
 setHref("nav1",SITE.header_link1_url);setHref("nav2",SITE.header_link2_url);setHref("nav3",SITE.header_link3_url);
 setText("heroButton",SITE.hero_button_text);setHref("heroButton",SITE.hero_button_link);
 setText("howButton",SITE.how_button_text);setHref("howButton",SITE.how_button_link);
 const logo=SITE.logo_url;if(logo){for(const id of ["brandMark","footerMark"]){const e=document.getElementById(id);if(e)e.innerHTML=`<img src="${escAttr(logo)}" alt="${escAttr(name)}" style="width:100%;height:100%;object-fit:contain;border-radius:inherit">`}}
 if(SITE.hero_image_url){const e=document.getElementById("heroCard");if(e){e.style.backgroundImage=`url("${escAttr(SITE.hero_image_url)}")`;e.style.backgroundSize="cover";e.style.backgroundPosition="center"}}
 document.documentElement.style.setProperty("--ink",SITE.primary_color||"#101010");document.documentElement.style.setProperty("--soft",SITE.page_background||"#f5f5f2");
 if(SITE.custom_css){let st=document.getElementById("customSiteCss");if(!st){st=document.createElement("style");st.id="customSiteCss";document.head.appendChild(st)}st.textContent=SITE.custom_css}
 [["noticeSection",SITE.show_notice],["offers",SITE.show_offer],["how",SITE.show_how],["referralSection",SITE.show_referral]].forEach(([id,s])=>{const e=document.getElementById(id);if(e)e.style.display=s===false?"none":""});
 for(const[id,url]of[["headerDm",SITE.whatsapp||C.whatsapp],["wa",SITE.whatsapp||C.whatsapp],["ig",SITE.instagram||C.instagram],["ms",SITE.messenger||C.messenger]])setHref(id,url||"#");
 const r=document.getElementById("refDm");if(r)r.href=dmLink("I have a referral code. Please verify it and tell me my eligible coupon.");
 const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();
}
function showError(t){const e=document.getElementById("products");if(e)e.innerHTML=`<div class="empty">${esc(t)}</div>`}
async function loadProducts(){const{data,error}=await sb.from("products").select("*").eq("published",true).order("created_at",{ascending:false});if(error){showError(error.message);return}allProducts=data||[];renderProducts()}
function renderProducts(){const grid=document.getElementById("products");if(!grid)return;const q=(document.getElementById("search")?.value||"").toLowerCase();const filtered=allProducts.filter(p=>(activeCategory==="All"||p.category===activeCategory)&&`${p.name} ${p.category} ${p.description||""}`.toLowerCase().includes(q));grid.innerHTML=filtered.map(card).join("");document.getElementById("empty")?.classList.toggle("hidden",filtered.length>0);renderCategories()}
function renderCategories(){const e=document.getElementById("categories");if(!e)return;const cats=["All",...new Set(allProducts.map(p=>p.category).filter(Boolean))];e.innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?"active":""}" onclick="activeCategory=${JSON.stringify(c)};renderProducts()">${esc(c)}</button>`).join("")}
function card(p){const cur=SITE.currency||C.currency||"৳";return `<a class="product-card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-image"><img src="${escAttr(p.image_url)}" alt="${escAttr(p.name)}" loading="lazy"></div><div class="product-info">${p.tag?`<span class="tag">${esc(p.tag)}</span>`:""}<div class="product-cat">${esc(p.category)}</div><div class="product-name">${esc(p.name)}</div><div><span class="price">${esc(cur)}${Number(p.price).toLocaleString()}</span>${p.old_price?`<span class="old">${esc(cur)}${Number(p.old_price).toLocaleString()}</span>`:""}</div></div></a>`}
async function loadNotices(){const e=document.getElementById("noticeTrack");if(!e)return;const{data}=await sb.from("notices").select("*").eq("active",true).order("sort_order",{ascending:true});e.innerHTML=(data?.length?data:[{title:"Welcome",message:"Shop our latest products and message us to order."}]).map(n=>`<span class="notice-item"><b>${esc(n.title)}</b> ${esc(n.message)}</span>`).join("")}
async function renderDetail(){const el=document.getElementById("productDetail");if(!el||!sb)return;const id=new URLSearchParams(location.search).get("id");if(!id)return;const{data:p,error}=await sb.from("products").select("*").eq("id",id).eq("published",true).maybeSingle();if(error||!p){el.innerHTML="<h1>Product not found</h1>";return}const cur=SITE.currency||C.currency||"৳";document.title=p.name+" — "+(SITE.store_name||"GRABZONE");el.innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${escAttr(p.image_url)}" alt="${escAttr(p.name)}"></div><div><div class="eyebrow">${esc(p.category)}</div><h1>${esc(p.name)}</h1>${p.tag?`<span class="tag">${esc(p.tag)}</span>`:""}<div class="detail-price">${esc(cur)}${Number(p.price).toLocaleString()} ${p.old_price?`<span class="old">${esc(cur)}${Number(p.old_price).toLocaleString()}</span>`:""}</div><p class="detail-desc">${esc(p.description||"")}</p><div class="dm-box"><strong>Have a referral code?</strong><p>Enter it below so our team can verify it and apply an eligible coupon.</p><input id="refCode" placeholder="Optional referral code"><a class="btn btn-dark btn-full" target="_blank" id="orderBtn">DM to Order</a></div></div></div>`;const btn=document.getElementById("orderBtn");btn.href=dmLink(`I want to order: ${p.name} | Price: ${cur}${p.price}`);document.getElementById("refCode").addEventListener("input",e=>btn.href=dmLink(`I want to order: ${p.name} | Price: ${cur}${p.price}${e.target.value.trim()?" | Referral code: "+e.target.value.trim():""}`))}
document.addEventListener("DOMContentLoaded",load);