const KEY="nova_store_v4"; const SETTINGS="nova_settings_v4";
const demoProducts=[
{id:"p1",name:"Portable Electric Kettle",category:"Home & Kitchen",price:990,oldPrice:1250,image:"https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=900&q=85",tag:"HOT DEAL",description:"Compact portable electric kettle for everyday use and travel.",published:true},
{id:"p2",name:"Plextone RX3 PLUS Wired Gaming Earphone",category:"Smart Gadgets",price:690,oldPrice:850,image:"https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=85",tag:"GAMING",description:"Wired gaming earphone for calls, gaming and everyday listening.",published:true},
{id:"p3",name:"Siren Alarm Lock For Security",category:"Security",price:790,oldPrice:990,image:"https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=900&q=85",tag:"POPULAR",description:"Compact alarm-style security lock. Message us to confirm availability.",published:true},
{id:"p4",name:"Mini Power Bank",category:"Smart Gadgets",price:790,oldPrice:950,image:"https://images.unsplash.com/photo-1609592424937-3e7f4e4b2e47?auto=format&fit=crop&w=900&q=85",tag:"NEW",description:"Portable backup power for everyday use.",published:true},
{id:"p5",name:"Portable Phone Stand",category:"Smart Gadgets",price:390,oldPrice:490,image:"https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=85",tag:"VALUE",description:"Foldable phone stand for desk and daily use.",published:true},
{id:"p6",name:"Kemei Grooming Kit",category:"Fashion Item",price:890,oldPrice:1090,image:"https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=900&q=85",tag:"BEST SELLER",description:"Multi-purpose grooming kit. Ask in DM for current stock and options.",published:true}
]
function getProducts(){try{let x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:demoProducts}catch{return demoProducts}}
function getSettings(){try{return {...window.STORE_DEFAULTS,...JSON.parse(localStorage.getItem(SETTINGS)||"{}")}}catch{return {...window.STORE_DEFAULTS}}}
function getNotices(){try{return JSON.parse(localStorage.getItem("nova_notices_v4"))||[{id:"n1",title:"Referral offer",text:"Approved partner referral codes can unlock ৳10–৳20 OFF after DM verification.",active:true},{id:"n2",title:"New drops",text:"New products and limited offers are added regularly.",active:true}]}catch{return []}}
function saveProducts(x){localStorage.setItem(KEY,JSON.stringify(x))}
function applyCommon(){const s=getSettings();document.querySelectorAll("#storeName,#footerName,#adminStoreName").forEach(e=>e.textContent=s.name);document.querySelectorAll("#year").forEach(e=>e.textContent=new Date().getFullYear());const links={headerDm:s.whatsapp,wa:s.whatsapp,ig:s.instagram,ms:s.messenger};for(const [id,url] of Object.entries(links)){const e=document.getElementById(id);if(e)e.href=url}const h=document.getElementById("refDm");if(h)h.href=dmLink("I have a referral code. Please verify it and tell me my eligible coupon.");renderNotices()}
function dmLink(text){const s=getSettings();return s.whatsapp+"?text="+encodeURIComponent(text)}
function renderNotices(){const el=document.getElementById("noticeTrack");if(!el)return;const ns=getNotices().filter(n=>n.active);el.innerHTML=(ns.length?ns:[{title:"Welcome",text:"Shop our latest products and message us to order."}]).map(n=>`<span class="notice-item"><b>${esc(n.title)}</b>${esc(n.text)}</span>`).join("")}
let activeCategory="All";
function renderProducts(){const grid=document.getElementById("products");if(!grid)return;const all=getProducts().filter(p=>p.published);const q=(document.getElementById("search")?.value||"").toLowerCase();const filtered=all.filter(p=>(activeCategory==="All"||p.category===activeCategory)&&`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q));grid.innerHTML=filtered.map(p=>card(p)).join("");document.getElementById("empty")?.classList.toggle("hidden",filtered.length>0);renderCategories(all)}
function renderCategories(all){const el=document.getElementById("categories");if(!el)return;const cats=["All",...new Set(all.map(p=>p.category).filter(Boolean))];el.innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?"active":""}" onclick="activeCategory='${escAttr(c)}';renderProducts()">${esc(c)}</button>`).join("")}
function card(p){return `<a class="product-card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-image"><img src="${escAttr(p.image)}" alt="${escAttr(p.name)}" loading="lazy"></div><div class="product-info">${p.tag?`<span class="tag">${esc(p.tag)}</span>`:""}<div class="product-cat">${esc(p.category)}</div><div class="product-name">${esc(p.name)}</div><div><span class="price">${getSettings().currency}${Number(p.price).toLocaleString()}</span>${p.oldPrice?`<span class="old">${getSettings().currency}${Number(p.oldPrice).toLocaleString()}</span>`:""}</div></div></a>`}
function focusSearch(){document.getElementById("search")?.focus()}
function renderDetail(){const el=document.getElementById("productDetail");if(!el)return;const id=new URLSearchParams(location.search).get("id");const p=getProducts().find(x=>x.id===id);if(!p){el.innerHTML="<h1>Product not found</h1>";return}document.title=p.name+" — "+getSettings().name;el.innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${escAttr(p.image)}" alt="${escAttr(p.name)}"></div><div><div class="eyebrow">${esc(p.category)}</div><h1>${esc(p.name)}</h1>${p.tag?`<span class="tag">${esc(p.tag)}</span>`:""}<div class="detail-price">${getSettings().currency}${Number(p.price).toLocaleString()} ${p.oldPrice?`<span class="old">${getSettings().currency}${Number(p.oldPrice).toLocaleString()}</span>`:""}</div><p class="detail-desc">${esc(p.description||"")}</p><div class="dm-box"><strong>Have a referral code?</strong><p>Enter it below so our team can verify it and apply an eligible coupon.</p><input id="refCode" placeholder="Optional referral code"><a class="btn btn-dark btn-full" target="_blank" href="${dmLink("I want to order: "+p.name+" | Price: "+getSettings().currency+p.price)}" id="orderBtn">DM to Order</a></div></div></div>`;document.getElementById("orderBtn").onclick=function(){const code=document.getElementById("refCode").value.trim();this.href=dmLink(`I want to order: ${p.name} | Price: ${getSettings().currency}${p.price}${code?" | Referral code: "+code:""}`)}}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function escAttr(x){return esc(x).replace(/`/g,"&#96;")}
document.addEventListener("DOMContentLoaded",()=>{applyCommon();renderProducts();renderDetail()})