/* GrabZone Multi-Vendor Marketplace layer.
 * This wrapper keeps the existing worker intact and adds vendor APIs, vendor auth,
 * storefronts, shipments, commission reporting and marketplace-aware order/tracking.
 */
import legacy from './worker.mjs';

const VENDOR_SCHEMA = [
`CREATE TABLE IF NOT EXISTS vendors (
 id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, business_name TEXT NOT NULL, brand_name TEXT NOT NULL,
 email TEXT NOT NULL, phone TEXT, logo_url TEXT, banner_url TEXT, description TEXT, tagline TEXT,
 accent_color TEXT DEFAULT '#ff6b00', status TEXT NOT NULL DEFAULT 'Active', shipping_fee REAL NOT NULL DEFAULT 130,
 commission_type TEXT NOT NULL DEFAULT 'percentage', commission_value REAL NOT NULL DEFAULT 10,
 homepage_visible INTEGER NOT NULL DEFAULT 1, featured INTEGER NOT NULL DEFAULT 0,
 social_links TEXT DEFAULT '{}', contact_info TEXT DEFAULT '{}', announcement TEXT,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL
)`,
`CREATE INDEX IF NOT EXISTS vendors_status_idx ON vendors(status,homepage_visible,featured)`,
`CREATE TABLE IF NOT EXISTS vendor_users (
 id TEXT PRIMARY KEY, vendor_id TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
 password_salt TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'vendor_admin', status TEXT NOT NULL DEFAULT 'Active',
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS vendor_users_vendor_idx ON vendor_users(vendor_id,status)`,
`CREATE TABLE IF NOT EXISTS vendor_sessions (
 token_hash TEXT PRIMARY KEY, vendor_user_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL,
 FOREIGN KEY(vendor_user_id) REFERENCES vendor_users(id) ON DELETE CASCADE
)`,
`CREATE TABLE IF NOT EXISTS vendor_products (
 product_id TEXT PRIMARY KEY, vendor_id TEXT NOT NULL, category TEXT, status TEXT NOT NULL DEFAULT 'Active',
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,
 FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS vendor_products_vendor_idx ON vendor_products(vendor_id,status)`,
`CREATE TABLE IF NOT EXISTS vendor_orders (
 id TEXT PRIMARY KEY, order_id TEXT NOT NULL, vendor_id TEXT NOT NULL, subtotal REAL NOT NULL DEFAULT 0,
 shipping_fee REAL NOT NULL DEFAULT 0, commission_amount REAL NOT NULL DEFAULT 0, vendor_earnings REAL NOT NULL DEFAULT 0,
 status TEXT NOT NULL DEFAULT 'Processing', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 UNIQUE(order_id,vendor_id), FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS vendor_orders_vendor_idx ON vendor_orders(vendor_id,created_at DESC)`,
`CREATE INDEX IF NOT EXISTS vendor_orders_order_idx ON vendor_orders(order_id)`,
`CREATE TABLE IF NOT EXISTS vendor_order_items (
 id TEXT PRIMARY KEY, vendor_order_id TEXT NOT NULL, order_item_id TEXT NOT NULL, product_id TEXT,
 quantity INTEGER NOT NULL, unit_price REAL NOT NULL DEFAULT 0, line_total REAL NOT NULL DEFAULT 0,
 FOREIGN KEY(vendor_order_id) REFERENCES vendor_orders(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS vendor_order_items_order_idx ON vendor_order_items(vendor_order_id)`,
`CREATE TABLE IF NOT EXISTS shipments (
 id TEXT PRIMARY KEY, order_id TEXT NOT NULL, vendor_id TEXT NOT NULL, courier TEXT, tracking_id TEXT,
 tracking_url TEXT, status TEXT NOT NULL DEFAULT 'Pending', note TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS shipments_order_idx ON shipments(order_id,created_at)`,
`CREATE INDEX IF NOT EXISTS shipments_vendor_idx ON shipments(vendor_id,created_at DESC)`,
`CREATE TABLE IF NOT EXISTS shipment_items (
 id TEXT PRIMARY KEY, shipment_id TEXT NOT NULL, order_item_id TEXT NOT NULL, quantity INTEGER NOT NULL,
 FOREIGN KEY(shipment_id) REFERENCES shipments(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS shipment_items_shipment_idx ON shipment_items(shipment_id)`,
`CREATE TABLE IF NOT EXISTS vendor_store_sections (
 id TEXT PRIMARY KEY, vendor_id TEXT NOT NULL, section_type TEXT NOT NULL, title TEXT, body TEXT,
 sort_order INTEGER NOT NULL DEFAULT 0, enabled INTEGER NOT NULL DEFAULT 1, data_json TEXT DEFAULT '{}',
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
)`,
`CREATE INDEX IF NOT EXISTS vendor_sections_idx ON vendor_store_sections(vendor_id,enabled,sort_order)`,
`CREATE TABLE IF NOT EXISTS marketplace_audit_log (
 id TEXT PRIMARY KEY, actor_type TEXT NOT NULL, actor_id TEXT, action TEXT NOT NULL, vendor_id TEXT,
 details TEXT, created_at TEXT NOT NULL
)`,
`CREATE TABLE IF NOT EXISTS marketplace_settings (
 id INTEGER PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 1, default_shipping REAL NOT NULL DEFAULT 130,
 show_brands INTEGER NOT NULL DEFAULT 1, show_vendor_badges INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL
)`,
`INSERT OR IGNORE INTO marketplace_settings(id,enabled,default_shipping,show_brands,show_vendor_badges,updated_at) VALUES(1,1,130,1,1,datetime('now'))`,
`ALTER TABLE products ADD COLUMN vendor_id TEXT`,
`ALTER TABLE order_items ADD COLUMN vendor_id TEXT`
];

let schemaPromise;
const now=()=>new Date().toISOString();
const json=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h}});
const text=(x,s=200,h={})=>new Response(x,{status:s,headers:h});
async function q(env,sql,params=[]){return env.DB.prepare(sql).bind(...params).all()}
async function one(env,sql,params=[]){return (await q(env,sql,params)).results?.[0]||null}
async function sha(v){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v))))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function pbkdf(p,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(s),iterations:100000,hash:'SHA-256'},k,256);return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cookie(req,name){const raw=req.headers.get('Cookie')||'';for(const p of raw.split(';')){const a=p.trim().split('=');if(a[0]===name)return decodeURIComponent(a.slice(1).join('='))}return ''}
async function hmac(secret,data){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(String(secret)),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(data)))}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function ub64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function sign(payload,secret){const p=b64(new TextEncoder().encode(JSON.stringify(payload)));return p+'.'+b64(await hmac(secret,p))}
async function verify(token,secret){if(!token||!secret)return null;const a=String(token).split('.');if(a.length!==2)return null;const expected=await hmac(secret,a[0]),got=ub64(a[1]);if(expected.length!==got.length)return null;let d=0;for(let i=0;i<expected.length;i++)d|=expected[i]^got[i];if(d)return null;try{const p=JSON.parse(new TextDecoder().decode(ub64(a[0])));return Number(p.exp)>Date.now()/1000?p:null}catch{return null}}
function slugify(v){return String(v||'').toLowerCase().normalize('NFKC').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'vendor'}
function clean(v,max=10000){return String(v??'').trim().slice(0,max)}
function secret(env){return String(env.MARKETPLACE_AUTH_SECRET||env.D1_AUTH_SECRET||env.GRABZONE_ADMIN_PASSWORD||'')}
async function ensureSchema(env){if(schemaPromise)return schemaPromise;schemaPromise=(async()=>{for(const sql of VENDOR_SCHEMA){try{await env.DB.prepare(sql).run()}catch(e){if(!String(sql).startsWith('ALTER TABLE'))throw e}}
 await env.DB.prepare("CREATE INDEX IF NOT EXISTS products_vendor_idx ON products(vendor_id,published)").run().catch(()=>{});
 await env.DB.prepare("CREATE INDEX IF NOT EXISTS order_items_vendor_idx ON order_items(vendor_id,order_id)").run().catch(()=>{});
 const gz=await one(env,"SELECT id FROM vendors WHERE slug='grabzone' LIMIT 1");
 if(!gz){const t=now(),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO vendors(id,slug,business_name,brand_name,email,status,shipping_fee,commission_value,homepage_visible,featured,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,'grabzone','GrabZone','GrabZone',String(env.GMAIL_FROM_EMAIL||'admin@grabzone.store'),'Active',130,0,1,1,'Official GrabZone products',t,t).run();await env.DB.prepare("UPDATE products SET vendor_id=? WHERE vendor_id IS NULL").bind(id).run();}
 else await env.DB.prepare("UPDATE products SET vendor_id=? WHERE vendor_id IS NULL").bind(gz.id).run();
 await env.DB.prepare("UPDATE vendor_products SET status='Active' WHERE status IS NULL").run().catch(()=>{});
 })().catch(e=>{schemaPromise=null;throw e});return schemaPromise}
async function admin(req,env){
 const a=req.headers.get('Authorization')||'',x=req.headers.get('X-GrabZone-Token')||'',bearer=a.startsWith('Bearer ')?a.slice(7):x;
 if(cookie(req,'gz_admin_session')){const raw=cookie(req,'gz_admin_session');const s=await one(env,"SELECT u.id,u.email FROM admin_sessions s JOIN admin_users u ON u.id=s.admin_user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1",[await sha(raw),now()]);if(s)return s}
 if(bearer){const p=await verify(bearer,secret(env));if(p?.sub)return{id:p.sub,email:p.email}}
 return null
}
async function vendorUser(req,env){const raw=cookie(req,'gz_vendor_session')||(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!raw)return null;const s=await one(env,"SELECT vu.id,vu.email,vu.vendor_id,vu.role,v.status AS vendor_status,v.brand_name,v.slug FROM vendor_sessions vs JOIN vendor_users vu ON vu.id=vs.vendor_user_id JOIN vendors v ON v.id=vu.vendor_id WHERE vs.token_hash=? AND vs.expires_at>? AND vu.status='Active' AND v.status='Active' LIMIT 1",[await sha(raw),now()]);return s||null}
async function audit(env,type,actor,action,vendor,details){await env.DB.prepare("INSERT INTO marketplace_audit_log(id,actor_type,actor_id,action,vendor_id,details,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),type,actor||null,action,vendor||null,details?JSON.stringify(details):null,now()).run().catch(()=>{})}
async function vendorAuth(req,env){await ensureSchema(env);if(req.method==='GET'){const u=await vendorUser(req,env);return json({authenticated:!!u,user:u?{id:u.id,email:u.email,vendor_id:u.vendor_id,brand_name:u.brand_name,slug:u.slug}:null})}if(req.method!=='POST')return json({error:'Method not allowed.'},405);let b={};try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)};if(b.action==='logout'){const raw=cookie(req,'gz_vendor_session')||(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(raw)await env.DB.prepare('DELETE FROM vendor_sessions WHERE token_hash=?').bind(await sha(raw)).run();return json({ok:true},200,{'Set-Cookie':'gz_vendor_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=None'})}const id=clean(b.identifier,200).toLowerCase(),pass=String(b.password||'');if(!id||!pass)return json({error:'Enter your vendor email and password.'},400);const u=await one(env,"SELECT vu.*,v.status vendor_status,v.brand_name,v.slug FROM vendor_users vu JOIN vendors v ON v.id=vu.vendor_id WHERE lower(vu.email)=lower(?) LIMIT 1",[id]);if(!u||u.status!=='Active'||u.vendor_status!=='Active')return json({error:'Vendor account is inactive or not found.'},401);if(await pbkdf(pass,u.password_salt)!==u.password_hash)return json({error:'Invalid vendor email or password.'},401);const raw=crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,''),exp=new Date(Date.now()+7*86400000).toISOString();await env.DB.prepare('INSERT INTO vendor_sessions(token_hash,vendor_user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(await sha(raw),u.id,exp,now()).run();await audit(env,'vendor_user',u.id,'LOGIN',u.vendor_id,{});return json({ok:true,user:{id:u.id,email:u.email,vendor_id:u.vendor_id,brand_name:u.brand_name,slug:u.slug},expires_at:exp,session_token:raw},200,{'Set-Cookie':'gz_vendor_session='+encodeURIComponent(raw)+'; Path=/; Max-Age=604800; HttpOnly; Secure; SameSite=None'})}
async function vendorList(req,env){const a=await admin(req,env);if(!a)return json({error:'Unauthorized.'},401);const rows=(await q(env,'SELECT * FROM vendors ORDER BY featured DESC,created_at DESC')).results||[];for(const v of rows){v.social_links=JSON.parse(v.social_links||'{}');v.contact_info=JSON.parse(v.contact_info||'{}');v.product_count=Number((await one(env,'SELECT COUNT(*) n FROM products WHERE vendor_id=?',[v.id]))?.n||0);v.order_count=Number((await one(env,'SELECT COUNT(*) n FROM vendor_orders WHERE vendor_id=?',[v.id]))?.n||0)}return json({vendors:rows})}
async function vendorCreate(req,env){const a=await admin(req,env);if(!a)return json({error:'Unauthorized.'},401);let b={};try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)}const name=clean(b.business_name||b.brand_name,120),brand=clean(b.brand_name||name,120),email=clean(b.email,200).toLowerCase(),password=String(b.password||'');if(name.length<2||brand.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return json({error:'Business/brand name, valid email and an 8+ character password are required.'},400);let slug=slugify(b.slug||brand),base=slug,n=1;while(await one(env,'SELECT id FROM vendors WHERE slug=?',[slug]))slug=base+'-'+(++n);const t=now(),id=crypto.randomUUID(),salt=crypto.randomUUID()+crypto.randomUUID();await env.DB.prepare('INSERT INTO vendors(id,slug,business_name,brand_name,email,phone,logo_url,banner_url,description,tagline,accent_color,status,shipping_fee,commission_type,commission_value,homepage_visible,featured,social_links,contact_info,announcement,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,slug,name,brand,email,clean(b.phone,40),clean(b.logo_url,1000),clean(b.banner_url,1000),clean(b.description,5000),clean(b.tagline,300),clean(b.accent_color,30)||'#ff6b00','Active',Math.max(0,Number(b.shipping_fee??130)),b.commission_type==='fixed'?'fixed':'percentage',Math.max(0,Number(b.commission_value??10)),b.homepage_visible===false?0:1,b.featured?1:0,JSON.stringify(b.social_links||{}),JSON.stringify(b.contact_info||{}),clean(b.announcement,500),t,t).run();const uid=crypto.randomUUID();await env.DB.prepare('INSERT INTO vendor_users(id,vendor_id,email,password_hash,password_salt,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid,id,email,await pbkdf(password,salt),salt,'vendor_admin','Active',t,t).run();await audit(env,'admin',a.id,'VENDOR_CREATED',id,{email,brand});return json({ok:true,vendor:{id,slug,brand_name:brand,email}})}
async function vendorUpdate(req,env){const a=await admin(req,env);if(!a)return json({error:'Unauthorized.'},401);const id=clean(req.params?.id||'',100);let b={};try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)}const v=await one(env,'SELECT * FROM vendors WHERE id=? OR slug=? LIMIT 1',[id,id]);if(!v)return json({error:'Vendor not found.'},404);const allowed=['business_name','brand_name','email','phone','logo_url','banner_url','description','tagline','accent_color','status','shipping_fee','commission_type','commission_value','homepage_visible','featured','announcement'];const sets=[],ps=[];for(const k of allowed)if(b[k]!==undefined){sets.push(k+'=?');ps.push(k==='status'?clean(b[k],30):k==='commission_type'?(b[k]==='fixed'?'fixed':'percentage'):['shipping_fee','commission_value'].includes(k)?Math.max(0,Number(b[k])):['homepage_visible','featured'].includes(k)?(b[k]?1:0):clean(b[k],10000))}if(b.social_links!==undefined){sets.push('social_links=?');ps.push(JSON.stringify(b.social_links||{}))}if(b.contact_info!==undefined){sets.push('contact_info=?');ps.push(JSON.stringify(b.contact_info||{}))}sets.push('updated_at=?');ps.push(now(),v.id);await env.DB.prepare('UPDATE vendors SET '+sets.join(',')+' WHERE id=?').bind(...ps).run();await audit(env,'admin',a.id,'VENDOR_UPDATED',v.id,b);return json({ok:true})}
async function vendorProducts(req,env){await ensureSchema(env);const a=await admin(req,env),u=await vendorUser(req,env);if(!a&&!u)return json({error:'Unauthorized.'},401);const vid=u?.vendor_id||clean(req.url&&new URL(req.url).searchParams.get('vendor_id'),100)||null;if(req.method==='GET'){const rows=(await q(env,'SELECT p.*,v.brand_name vendor_name,v.slug vendor_slug FROM products p LEFT JOIN vendors v ON v.id=p.vendor_id '+(vid?'WHERE p.vendor_id=? ':'')+'ORDER BY p.created_at DESC',[...(vid?[vid]:[])])).results||[];return json({products:rows})}let b={};try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)};if(!a&&!u)return json({error:'Unauthorized.'},401);if(req.method==='POST'){const vendorId=u?.vendor_id||clean(b.vendor_id,100);if(!vendorId)return json({error:'Vendor is required.'},400);const v=await one(env,'SELECT * FROM vendors WHERE id=? AND status=\'Active\'',[vendorId]);if(!v)return json({error:'Vendor not found.'},404);const id=crypto.randomUUID(),t=now();const name=clean(b.name,300),price=Math.max(0,Number(b.price||0));if(!name||price<0)return json({error:'Product name and valid price are required.'},400);await env.DB.prepare('INSERT INTO products(id,name,category,price,old_price,image_url,tag,description,published,vendor_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,name,clean(b.category,120)||'General',price,b.old_price===''?null:Number(b.old_price??null),clean(b.image_url,2000),clean(b.tag,100),clean(b.description,10000),b.published===false?0:1,vendorId,t,t).run();await env.DB.prepare('INSERT OR REPLACE INTO vendor_products(product_id,vendor_id,category,status,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(id,vendorId,clean(b.category,120),'Active',t,t).run();return json({ok:true,id})}if(req.method==='PATCH'){const id=clean(b.id,100),p=await one(env,'SELECT * FROM products WHERE id=? LIMIT 1',[id]);if(!p)return json({error:'Product not found.'},404);if(u&&p.vendor_id!==u.vendor_id)return json({error:'Forbidden.'},403);const fields=['name','category','price','old_price','image_url','tag','description','published'];const sets=[],ps=[];for(const k of fields)if(b[k]!==undefined){sets.push(k+'=?');ps.push(['price','old_price'].includes(k)?(b[k]===''?null:Number(b[k])):k==='published'?(b[k]?1:0):clean(b[k],10000))}if(sets.length){sets.push('updated_at=?');ps.push(now(),id);await env.DB.prepare('UPDATE products SET '+sets.join(',')+' WHERE id=?').bind(...ps).run()}return json({ok:true})}return json({error:'Method not allowed.'},405)}
async function dashboard(req,env){const u=await vendorUser(req,env);if(!u)return json({error:'Unauthorized.'},401);const [products,orders,sales,shipments]=await Promise.all([one(env,'SELECT COUNT(*) n FROM products WHERE vendor_id=?',[u.vendor_id]),one(env,'SELECT COUNT(*) n FROM vendor_orders WHERE vendor_id=?',[u.vendor_id]),one(env,'SELECT COALESCE(SUM(subtotal),0) n,COALESCE(SUM(commission_amount),0) commission,COALESCE(SUM(vendor_earnings),0) earnings FROM vendor_orders WHERE vendor_id=?',[u.vendor_id]),one(env,'SELECT COUNT(*) n FROM shipments WHERE vendor_id=? AND status<>\'Delivered\'',[u.vendor_id])]);return json({vendor:{id:u.vendor_id,brand_name:u.brand_name,slug:u.slug},metrics:{products:Number(products?.n||0),orders:Number(orders?.n||0),sales:Number(sales?.n||0),commission:Number(sales?.commission||0),earnings:Number(sales?.earnings||0),open_shipments:Number(shipments?.n||0)}})}
async function orders(req,env){const a=await admin(req,env),u=await vendorUser(req,env);if(!a&&!u)return json({error:'Unauthorized.'},401);const vid=u?.vendor_id||new URL(req.url).searchParams.get('vendor_id');if(!vid)return json({error:'Vendor is required.'},400);const rows=(await q(env,`SELECT vo.*,o.order_number,o.public_tracking_id,o.customer_name,o.email,o.phone,o.address,o.district,o.division,o.status order_status,v.brand_name FROM vendor_orders vo JOIN orders o ON o.id=vo.order_id JOIN vendors v ON v.id=vo.vendor_id WHERE vo.vendor_id=? ORDER BY vo.created_at DESC`,[vid])).results||[];for(const r of rows){r.items=(await q(env,'SELECT voi.*,oi.product_name,oi.image_url FROM vendor_order_items voi JOIN order_items oi ON oi.id=voi.order_item_id WHERE voi.vendor_order_id=?',[r.id])).results||[];r.shipments=(await q(env,'SELECT * FROM shipments WHERE order_id=? AND vendor_id=? ORDER BY created_at',[r.order_id,vid])).results||[]}return json({orders:rows})}
async function shipment(req,env){const a=await admin(req,env),u=await vendorUser(req,env);if(!a&&!u)return json({error:'Unauthorized.'},401);if(req.method!=='POST')return json({error:'Method not allowed.'},405);let b={};try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)}const order=await one(env,'SELECT vo.*,o.order_number,o.email,o.customer_name,o.public_tracking_id FROM vendor_orders vo JOIN orders o ON o.id=vo.order_id WHERE vo.id=? LIMIT 1',[clean(b.vendor_order_id,100)]);if(!order)return json({error:'Vendor order not found.'},404);if(u&&order.vendor_id!==u.vendor_id)return json({error:'Forbidden.'},403);const courier=clean(b.courier,100),tracking=clean(b.tracking_id,200);if(!courier||!tracking)return json({error:'Courier and tracking ID are required.'},400);const st=['Pending','Processing','Picked Up','In Transit','Out for Delivery','Delivered','Failed','Returned','Cancelled'].includes(b.status)?b.status:'Processing',t=now(),sid=crypto.randomUUID();await env.DB.prepare('INSERT INTO shipments(id,order_id,vendor_id,courier,tracking_id,tracking_url,status,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(sid,order.order_id,order.vendor_id,courier,tracking,clean(b.tracking_url,1000),st,clean(b.note,1000),t,t).run();const ids=Array.isArray(b.order_item_ids)?b.order_item_ids:[];for(const itemId of ids){const oi=await one(env,'SELECT id,quantity FROM order_items WHERE id=? AND order_id=?',[itemId,order.order_id]);if(oi)await env.DB.prepare('INSERT INTO shipment_items(id,shipment_id,order_item_id,quantity) VALUES(?,?,?,?)').bind(crypto.randomUUID(),sid,itemId,Math.min(Number(b.quantities?.[itemId]||oi.quantity),oi.quantity)).run()}await env.DB.prepare('UPDATE vendor_orders SET status=?,updated_at=? WHERE id=?').bind(st,t,order.id).run();await recomputeParent(env,order.order_id);await audit(env,u?'vendor_user':'admin',u?.id||a.id,'SHIPMENT_CREATED',order.vendor_id,{shipment_id:sid,courier,tracking,status:st});await notifyCustomer(env,order.order_number);return json({ok:true,shipment_id:sid})}
async function recomputeParent(env,orderId){const rows=(await q(env,'SELECT status FROM vendor_orders WHERE order_id=?',[orderId])).results||[];if(!rows.length)return;const statuses=rows.map(x=>String(x.status));let status='Processing';if(statuses.every(x=>x==='Delivered'))status='Delivered';else if(statuses.every(x=>['Cancelled','Returned'].includes(x)))status='Cancelled';else if(statuses.some(x=>['In Transit','Out for Delivery','Picked Up'].includes(x)))status='Shipped';else if(statuses.some(x=>x==='Processing'))status='Processing';await env.DB.prepare('UPDATE orders SET status=?,updated_at=? WHERE id=?').bind(status,now(),orderId).run()}
async function notifyCustomer(env,orderNumber){try{const adminUser=await one(env,'SELECT id,email,password_hash FROM admin_users ORDER BY created_at LIMIT 1');if(!adminUser)return;const tok=await sign({sub:adminUser.id,email:adminUser.email,exp:Math.floor(Date.now()/1000)+300},secret(env));const url=new URL('/api/send-order-email',env.PUBLIC_BASE_URL||'http://grabzone.internal');await legacy.fetch(new Request(url.toString(),{method:'POST',headers:{'Content-Type':'application/json','X-GrabZone-Token':tok},body:JSON.stringify({orderNumber})}),env)}catch(e){console.warn('vendor customer email failed',e)}}
async function adminOverview(req,env){const a=await admin(req,env);if(!a)return json({error:'Unauthorized.'},401);const vendors=(await q(env,'SELECT v.*,COALESCE(SUM(vo.subtotal),0) sales,COALESCE(SUM(vo.commission_amount),0) commission,COALESCE(SUM(vo.vendor_earnings),0) earnings,COUNT(DISTINCT vo.id) orders FROM vendors v LEFT JOIN vendor_orders vo ON vo.vendor_id=v.id GROUP BY v.id ORDER BY sales DESC')).results||[];const totals=vendors.reduce((x,v)=>{x.sales+=Number(v.sales||0);x.commission+=Number(v.commission||0);x.earnings+=Number(v.earnings||0);x.orders+=Number(v.orders||0);return x},{sales:0,commission:0,earnings:0,orders:0});return json({vendors,totals})}
async function storefront(req,env){await ensureSchema(env);const u=new URL(req.url),slug=clean(u.searchParams.get('slug'),100);const v=await one(env,'SELECT * FROM vendors WHERE slug=? AND status=\'Active\' LIMIT 1',[slug]);if(!v)return json({error:'Store not found.'},404);const products=(await q(env,'SELECT * FROM products WHERE vendor_id=? AND published=1 ORDER BY created_at DESC',[v.id])).results||[];const sections=(await q(env,'SELECT * FROM vendor_store_sections WHERE vendor_id=? AND enabled=1 ORDER BY sort_order',[v.id])).results||[];return json({vendor:{...v,social_links:JSON.parse(v.social_links||'{}'),contact_info:JSON.parse(v.contact_info||'{}')},products,sections})}
async function brands(req,env){await ensureSchema(env);const rows=(await q(env,'SELECT id,slug,business_name,brand_name,logo_url,banner_url,description,tagline,accent_color,featured FROM vendors WHERE status=\'Active\' AND homepage_visible=1 ORDER BY featured DESC,brand_name')).results||[];return json({brands:rows})}
async function marketplaceProducts(req,env){await ensureSchema(env);const u=new URL(req.url),vendor=clean(u.searchParams.get('vendor'),100),category=clean(u.searchParams.get('category'),100);let sql='SELECT p.*,v.brand_name vendor_name,v.slug vendor_slug,v.logo_url vendor_logo,v.accent_color vendor_accent FROM products p JOIN vendors v ON v.id=p.vendor_id WHERE p.published=1 AND v.status=\'Active\'',ps=[];if(vendor){sql+=' AND (v.slug=? OR v.id=?)';ps.push(vendor,vendor)}if(category){sql+=' AND lower(p.category)=lower(?)';ps.push(category)}sql+=' ORDER BY p.created_at DESC';return json({products:(await q(env,sql,ps)).results||[]})}
async function createMarketplaceOrder(env,payload){const p=payload.payload||payload;if(!Array.isArray(p.items)||!p.items.length)throw new Error('Your order is empty.');const phone=clean(p.phone,40).replace(/\D/g,'');if(!/^01[3-9]\d{8}$/.test(phone))throw new Error('Please enter a valid Bangladesh mobile number.');const t=now(),n=Number((await one(env,'SELECT COALESCE(MAX(order_no),0)+1 n FROM orders'))?.n||1),id=crypto.randomUUID(),orderNumber='GZ-'+String(n).padStart(4,'0'),tracking='GZ-'+crypto.randomUUID().replace(/-/g,'').slice(0,16).toUpperCase();const vendorMap=new Map(),items=[];let subtotal=0;for(const x of p.items){const pr=await one(env,'SELECT p.*,v.id vendor_id,v.brand_name,v.shipping_fee,v.commission_type,v.commission_value FROM products p JOIN vendors v ON v.id=p.vendor_id WHERE p.id=? AND p.published=1 AND v.status=\'Active\' LIMIT 1',[clean(x.product_id,100)]);if(!pr)throw new Error('One of the selected products is no longer available.');const qty=Math.max(1,parseInt(x.quantity,10)||1),unit=Number(pr.price||0),line=unit*qty;subtotal+=line;const oi={id:crypto.randomUUID(),product_id:pr.id,vendor_id:pr.vendor_id,product_name:pr.name,image_url:pr.image_url,quantity:qty,unit_price:unit,line_total:line};items.push(oi);if(!vendorMap.has(pr.vendor_id))vendorMap.set(pr.vendor_id,{vendor:pr,items:[],subtotal:0});vendorMap.get(pr.vendor_id).items.push(oi);vendorMap.get(pr.vendor_id).subtotal+=line}
let discount=0;const code=clean(p.referral_code,100).toUpperCase();if(code){const r=await one(env,'SELECT * FROM referral_codes WHERE upper(code)=upper(?) AND active=1 LIMIT 1',[code]);if(r){discount=r.benefit_type==='percentage'?Math.round(subtotal*Number(r.benefit_value||0)/100*100)/100:Number(r.benefit_value||0);if(r.max_discount_amount!==null)discount=Math.min(discount,Number(r.max_discount_amount));discount=Math.min(subtotal,Math.max(0,discount))}}
let shipping=0;for(const g of vendorMap.values())shipping+=Math.max(0,Number(g.vendor.shipping_fee??130));const total=Math.max(0,subtotal+shipping-discount);await env.DB.prepare('INSERT INTO orders(id,order_no,order_number,customer_name,email,phone,division,district,upazila,address,referral_code,referral_discount,discount_amount,payment_method,shipping_charge,subtotal,total,status,public_tracking_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,n,orderNumber,clean(p.customer_name,160),clean(p.email,200).toLowerCase(),phone,clean(p.division,100),clean(p.district,100),clean(p.upazila,100),clean(p.address,1000),code||null,discount,discount,'Cash on Delivery',shipping,subtotal,total,'New',tracking,t,t).run();for(const i of items){await env.DB.prepare('INSERT INTO order_items(id,order_id,product_id,product_name,image_url,quantity,unit_price,line_total,vendor_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(i.id,id,i.product_id,i.product_name,i.image_url,i.quantity,i.unit_price,i.line_total,i.vendor_id).run()}
for(const g of vendorMap.values()){const v=g.vendor,comm=v.commission_type==='fixed'?Number(v.commission_value||0):g.subtotal*Number(v.commission_value||0)/100,voId=crypto.randomUUID(),earn=Math.max(0,g.subtotal-comm);await env.DB.prepare('INSERT INTO vendor_orders(id,order_id,vendor_id,subtotal,shipping_fee,commission_amount,vendor_earnings,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(voId,id,v.id,g.subtotal,Number(v.shipping_fee||0),comm,earn,'Processing',t,t).run();for(const i of g.items)await env.DB.prepare('INSERT INTO vendor_order_items(id,vendor_order_id,order_item_id,product_id,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),voId,i.id,i.product_id,i.quantity,i.unit_price,i.line_total).run()}
await audit(env,'customer',phone,'MARKETPLACE_ORDER_CREATED',null,{order_id:id,order_number:orderNumber,vendors:[...vendorMap.keys()]});return{data:{id,order_number:orderNumber,public_tracking_id:tracking,subtotal,shipping_charge:shipping,total,status:'New',vendor_count:vendorMap.size}}}
async function track(req,env){await ensureSchema(env);const id=clean(new URL(req.url).searchParams.get('tracking_id'),100).toUpperCase(),o=await one(env,'SELECT * FROM orders WHERE upper(public_tracking_id)=upper(?) OR upper(order_number)=upper(?) LIMIT 1',[id,id]);if(!o)return json({error:'Order not found.'},404);const vendors=(await q(env,'SELECT vo.*,v.brand_name,v.slug,v.logo_url FROM vendor_orders vo JOIN vendors v ON v.id=vo.vendor_id WHERE vo.order_id=?',[o.id])).results||[];for(const v of vendors){v.items=(await q(env,'SELECT voi.*,oi.product_name,oi.image_url FROM vendor_order_items voi JOIN order_items oi ON oi.id=voi.order_item_id WHERE voi.vendor_order_id=?',[v.id])).results||[];v.shipments=(await q(env,'SELECT s.* FROM shipments s WHERE s.order_id=? AND s.vendor_id=? ORDER BY s.created_at',[o.id,v.vendor_id])).results||[];for(const s of v.shipments)s.items=(await q(env,'SELECT si.*,oi.product_name FROM shipment_items si JOIN order_items oi ON oi.id=si.order_item_id WHERE si.shipment_id=?',[s.id])).results||[]}return json({order:{order_number:o.order_number,tracking_id:o.public_tracking_id,status:o.status,created_at:o.created_at,updated_at:o.updated_at,subtotal:Number(o.subtotal||0),shipping_charge:Number(o.shipping_charge||0),total:Number(o.total||0)},vendors})}
async function api(req,env){const p=new URL(req.url).pathname;await ensureSchema(env);
 if(p==='/api/vendor-auth')return vendorAuth(req,env);
 if(p==='/api/marketplace/brands')return brands(req,env);
 if(p==='/api/marketplace/products')return marketplaceProducts(req,env);
 if(p==='/api/marketplace/store')return storefront(req,env);
 if(p==='/api/marketplace/track')return track(req,env);
 if(p==='/api/vendor/admin/vendors'&&req.method==='GET')return vendorList(req,env);
 if(p==='/api/vendor/admin/vendors'&&req.method==='POST')return vendorCreate(req,env);
 if(p.startsWith('/api/vendor/admin/vendors/')&&req.method==='PATCH'){req.params={id:p.split('/').pop()};return vendorUpdate(req,env)}
 if(p==='/api/vendor/admin/overview')return adminOverview(req,env);
 if(p==='/api/vendor/products')return vendorProducts(req,env);
 if(p==='/api/vendor/dashboard')return dashboard(req,env);
 if(p==='/api/vendor/orders')return orders(req,env);
 if(p==='/api/vendor/shipments')return shipment(req,env);
 if(p==='/api/marketplace/order'&&req.method==='POST'){let b={};try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)};try{return json(await createMarketplaceOrder(env,b))}catch(e){return json({error:e.message||'Could not create order.'},400)}}
 if(p==='/api/d1'&&req.method==='POST'){
  const clone=req.clone();let b={};try{b=await clone.json()}catch{}
  if(String(b.fn||'')==='create_public_order'&&(b.args?.payload?.marketplace===true||b.args?.marketplace===true||b.marketplace===true))try{return json(await createMarketplaceOrder(env,b.args||b))}catch(e){return json({error:e.message||'Could not create order.'},400);
  }
  if(String(b.fn||'')==='track_public_order'){const id=clean(b.args?.p_tracking_id||b.p_tracking_id,100);const has=await one(env,'SELECT id FROM orders WHERE (upper(public_tracking_id)=upper(?) OR upper(order_number)=upper(?)) AND EXISTS(SELECT 1 FROM vendor_orders WHERE order_id=orders.id) LIMIT 1',[id,id]);if(has){const r=await fetch(new URL('/api/marketplace/track?tracking_id='+encodeURIComponent(id),req.url));const d=await r.json();return json({data:{...(d.order||{}),vendor_breakdown:d.vendors||[],trackingId:d.order?.tracking_id,orderNumber:d.order?.order_number,status:d.order?.status,createdAt:d.order?.created_at,updatedAt:d.order?.updated_at}})}}
  return legacy.fetch(req,env);
 }
 if(p==='/api/send-order-email'&&req.method==='POST'){const clone=req.clone();let b={};try{b=await clone.json()}catch{};const num=clean(b.orderNumber,100);const o=num?await one(env,'SELECT id FROM orders WHERE order_number=? LIMIT 1',[num]):null;if(o&&await one(env,'SELECT id FROM vendor_orders WHERE order_id=? LIMIT 1',[o.id])){await notifyCustomer(env,num);return json({ok:true,marketplace:true})}return legacy.fetch(req,env)}
 return null;
}
async function handle(req,env){try{if(req.method==='OPTIONS'){const h=new Headers({'Access-Control-Allow-Origin':req.headers.get('Origin')||'*','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization,X-GrabZone-Token'});return new Response(null,{status:204,headers:h})}const r=await api(req,env);if(r){const h=new Headers(r.headers),o=req.headers.get('Origin');h.set('Access-Control-Allow-Origin',o||'*');h.set('Access-Control-Allow-Credentials','true');h.append('Vary','Origin');return new Response(r.body,{status:r.status,headers:h})}const r2=await legacy.fetch(req,env);return r2}catch(e){console.error(e);return json({error:e.message||'Internal server error.'},500)}}
export default {fetch:handle};
